// web/src/lib/components/overlays/CommandPalette.svelte
<script lang="ts">
	import { goto } from '$app/navigation';
	import { formatShortcut } from '$lib/utils/platform';

	interface Props {
		open: boolean;
		onClose: () => void;
	}

	let { open, onClose }: Props = $props();

	let searchQuery = $state('');
	let selectedIndex = $state(0);
	let inputRef = $state<HTMLInputElement | null>(null);

	interface Command {
		id: string;
		label: string;
		description?: string;
		icon: string;
		shortcut?: string;
		action: () => void;
		category: string;
	}

	const commands: Command[] = [
		// Tasks
		{
			id: 'new-task',
			label: 'New Task',
			description: 'Create a new task',
			icon: '\u002B', // +
			shortcut: 'N',
			action: () => {
				onClose();
				window.dispatchEvent(new CustomEvent('orc:new-task'));
			},
			category: 'Tasks'
		},
		{
			id: 'go-tasks',
			label: 'Go to Tasks',
			description: 'View all tasks',
			icon: '\u25A0', // ■
			action: () => {
				onClose();
				goto('/');
			},
			category: 'Navigation'
		},
		{
			id: 'go-dashboard',
			label: 'Go to Dashboard',
			description: 'Overview and quick stats',
			icon: '\u25A0', // ■
			action: () => {
				onClose();
				goto('/dashboard');
			},
			category: 'Navigation'
		},
		// Environment
		{
			id: 'go-environment',
			label: 'Go to Environment',
			description: 'Claude ecosystem overview',
			icon: '\u2699', // ⚙
			action: () => {
				onClose();
				goto('/environment');
			},
			category: 'Environment'
		},
		{
			id: 'go-skills',
			label: 'Go to Skills',
			description: 'Manage Claude skills',
			icon: '\u26A1', // ⚡
			action: () => {
				onClose();
				goto('/environment/claude/skills');
			},
			category: 'Environment'
		},
		{
			id: 'go-hooks',
			label: 'Go to Hooks',
			description: 'Configure event hooks',
			icon: '\u21BB', // ↻
			action: () => {
				onClose();
				goto('/environment/claude/hooks');
			},
			category: 'Environment'
		},
		{
			id: 'go-agents',
			label: 'Go to Agents',
			description: 'Sub-agent configurations',
			icon: '\u2726', // ✦
			action: () => {
				onClose();
				goto('/environment/claude/agents');
			},
			category: 'Environment'
		},
		{
			id: 'go-tools',
			label: 'Go to Tools',
			description: 'Tool permissions',
			icon: '\u2692', // ⚒
			action: () => {
				onClose();
				goto('/environment/claude/tools');
			},
			category: 'Environment'
		},
		{
			id: 'go-mcp',
			label: 'Go to MCP Servers',
			description: 'Manage MCP integrations',
			icon: '\u229A', // ⊚
			action: () => {
				onClose();
				goto('/environment/claude/mcp');
			},
			category: 'Environment'
		},
		{
			id: 'go-prompts',
			label: 'Go to Prompts',
			description: 'Manage prompt templates',
			icon: '\u2630', // ☰
			action: () => {
				onClose();
				goto('/environment/orchestrator/prompts');
			},
			category: 'Environment'
		},
		{
			id: 'go-scripts',
			label: 'Go to Scripts',
			description: 'Script registry',
			icon: '\u2630', // ☰
			action: () => {
				onClose();
				goto('/environment/orchestrator/scripts');
			},
			category: 'Environment'
		},
		{
			id: 'go-automation',
			label: 'Go to Automation',
			description: 'Orc configuration',
			icon: '\u2699', // ⚙
			action: () => {
				onClose();
				goto('/environment/orchestrator/automation');
			},
			category: 'Environment'
		},
		{
			id: 'go-export',
			label: 'Go to Export',
			description: 'Export configuration',
			icon: '\u2B06', // ⬆
			action: () => {
				onClose();
				goto('/environment/orchestrator/export');
			},
			category: 'Environment'
		},
		{
			id: 'go-docs',
			label: 'Go to Documentation',
			description: 'CLAUDE.md hierarchy',
			icon: '\u2630', // ☰
			action: () => {
				onClose();
				goto('/environment/docs');
			},
			category: 'Environment'
		},
		{
			id: 'go-preferences',
			label: 'Go to Preferences',
			description: 'Personal and global settings',
			icon: '\u2699', // ⚙
			action: () => {
				onClose();
				goto('/preferences');
			},
			category: 'Settings'
		},
		// Projects & View
		{
			id: 'switch-project',
			label: 'Switch Project',
			description: 'Change active project',
			icon: '\u21C4', // ⇄
			shortcut: 'P',
			action: () => {
				onClose();
				window.dispatchEvent(new CustomEvent('orc:switch-project'));
			},
			category: 'Projects'
		},
		{
			id: 'toggle-sidebar',
			label: 'Toggle Sidebar',
			description: 'Show/hide navigation',
			icon: '\u2630', // ☰
			shortcut: 'B',
			action: () => {
				onClose();
				window.dispatchEvent(new CustomEvent('orc:toggle-sidebar'));
			},
			category: 'View'
		}
	];

	const filteredCommands = $derived(() => {
		if (!searchQuery.trim()) return commands;
		const query = searchQuery.toLowerCase();
		return commands.filter(
			(cmd) =>
				cmd.label.toLowerCase().includes(query) ||
				cmd.description?.toLowerCase().includes(query) ||
				cmd.category.toLowerCase().includes(query)
		);
	});

	// Highlight matching text in search results
	function highlightMatch(text: string, query: string): string {
		if (!query.trim()) return text;
		const regex = new RegExp(`(${escapeRegex(query)})`, 'gi');
		return text.replace(regex, '<mark>$1</mark>');
	}

	function escapeRegex(str: string): string {
		return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
	}

	// Group by category
	const groupedCommands = $derived(() => {
		const filtered = filteredCommands();
		const groups: Record<string, Command[]> = {};
		for (const cmd of filtered) {
			if (!groups[cmd.category]) {
				groups[cmd.category] = [];
			}
			groups[cmd.category].push(cmd);
		}
		return groups;
	});

	// Flat list for keyboard navigation
	const flatCommands = $derived(() => filteredCommands());

	$effect(() => {
		if (open && inputRef) {
			inputRef.focus();
			searchQuery = '';
			selectedIndex = 0;
		}
	});

	function handleKeydown(e: KeyboardEvent) {
		const cmds = flatCommands();

		switch (e.key) {
			case 'ArrowDown':
				e.preventDefault();
				selectedIndex = Math.min(selectedIndex + 1, cmds.length - 1);
				break;
			case 'ArrowUp':
				e.preventDefault();
				selectedIndex = Math.max(selectedIndex - 1, 0);
				break;
			case 'Enter':
				e.preventDefault();
				if (cmds[selectedIndex]) {
					cmds[selectedIndex].action();
				}
				break;
			case 'Escape':
				onClose();
				break;
		}
	}

	function handleBackdropClick(e: MouseEvent) {
		if (e.target === e.currentTarget) {
			onClose();
		}
	}

	// Reset selected index when search changes
	$effect(() => {
		searchQuery;
		selectedIndex = 0;
	});
</script>

{#if open}
	<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
	<div
		class="palette-backdrop"
		role="dialog"
		aria-modal="true"
		aria-label="Command palette"
		tabindex="-1"
		onclick={handleBackdropClick}
		onkeydown={handleKeydown}
	>
		<div class="palette-content">
			<!-- Search Input -->
			<div class="palette-search">
				<svg class="search-icon" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
					<circle cx="11" cy="11" r="8" />
					<path d="m21 21-4.35-4.35" />
				</svg>
				<input
					bind:this={inputRef}
					bind:value={searchQuery}
					type="text"
					placeholder="Type a command or search..."
					class="search-input"
					aria-label="Search commands"
				/>
				<kbd class="search-hint">esc</kbd>
			</div>

			<!-- Results -->
			<div class="palette-results">
				{#each Object.entries(groupedCommands()) as [category, cmds]}
					<div class="result-group">
						<div class="group-label">{category}</div>
						{#each cmds as cmd, i}
							{@const globalIndex = flatCommands().indexOf(cmd)}
							<button
								class="result-item"
								class:selected={globalIndex === selectedIndex}
								onclick={() => cmd.action()}
								onmouseenter={() => (selectedIndex = globalIndex)}
							>
								<span class="item-icon">{cmd.icon}</span>
								<div class="item-content">
								<span class="item-label">{@html highlightMatch(cmd.label, searchQuery)}</span>
								{#if cmd.description}
									<span class="item-description">{@html highlightMatch(cmd.description, searchQuery)}</span>
								{/if}
							</div>
								{#if cmd.shortcut}
									<kbd class="item-shortcut">{formatShortcut(cmd.shortcut)}</kbd>
								{/if}
							</button>
						{/each}
					</div>
				{:else}
					<div class="no-results">
						<span class="no-results-icon">?</span>
						<p>No commands found</p>
					</div>
				{/each}
			</div>

			<!-- Footer -->
			<div class="palette-footer">
				<div class="footer-hint">
					<kbd>\u2191</kbd><kbd>\u2193</kbd> to navigate
				</div>
				<div class="footer-hint">
					<kbd>\u21B5</kbd> to select
				</div>
			</div>
		</div>
	</div>
{/if}

<style>
	.palette-backdrop {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.6);
		backdrop-filter: blur(4px);
		display: flex;
		align-items: flex-start;
		justify-content: center;
		padding: var(--space-16) var(--space-4);
		z-index: 1100;
		animation: fade-in var(--duration-fast) var(--ease-out);
	}

	.palette-content {
		background: var(--bg-secondary);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-xl);
		box-shadow: var(--shadow-2xl);
		width: 100%;
		max-width: 560px;
		max-height: 70vh;
		overflow: hidden;
		display: flex;
		flex-direction: column;
		animation: modal-content-in var(--duration-fast) var(--ease-out);
	}

	/* Search */
	.palette-search {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		padding: var(--space-4);
		border-bottom: 1px solid var(--border-subtle);
	}

	.search-icon {
		flex-shrink: 0;
		color: var(--text-muted);
	}

	.search-input {
		flex: 1;
		background: transparent;
		border: none;
		font-size: var(--text-base);
		color: var(--text-primary);
		outline: none;
	}

	.search-input::placeholder {
		color: var(--text-muted);
	}

	.search-hint {
		flex-shrink: 0;
		padding: var(--space-0-5) var(--space-1-5);
		background: var(--bg-tertiary);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-sm);
		font-family: var(--font-mono);
		font-size: var(--text-2xs);
		color: var(--text-muted);
	}

	/* Results */
	.palette-results {
		flex: 1;
		overflow-y: auto;
		padding: var(--space-2);
	}

	.result-group {
		margin-bottom: var(--space-2);
	}

	.group-label {
		padding: var(--space-2) var(--space-3);
		font-size: var(--text-2xs);
		font-weight: var(--font-semibold);
		text-transform: uppercase;
		letter-spacing: var(--tracking-wider);
		color: var(--text-muted);
	}

	.result-item {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		width: 100%;
		padding: var(--space-2-5) var(--space-3);
		background: transparent;
		border: none;
		border-radius: var(--radius-md);
		text-align: left;
		cursor: pointer;
		transition: background var(--duration-fast) var(--ease-out);
	}

	.result-item:hover,
	.result-item.selected {
		background: var(--bg-tertiary);
	}

	.result-item.selected {
		outline: 1px solid var(--accent-muted);
	}

	.item-icon {
		flex-shrink: 0;
		width: 24px;
		height: 24px;
		display: flex;
		align-items: center;
		justify-content: center;
		background: var(--bg-tertiary);
		border-radius: var(--radius-sm);
		font-size: var(--text-sm);
		color: var(--text-secondary);
	}

	.result-item.selected .item-icon {
		background: var(--accent-subtle);
		color: var(--accent-primary);
	}

	.item-content {
		flex: 1;
		min-width: 0;
	}

	.item-label {
		display: block;
		font-size: var(--text-sm);
		font-weight: var(--font-medium);
		color: var(--text-primary);
	}

	.item-description {
		display: block;
		font-size: var(--text-xs);
		color: var(--text-muted);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	/* Search match highlighting */
	.item-label :global(mark),
	.item-description :global(mark) {
		background: var(--accent-subtle);
		color: var(--accent-primary);
		border-radius: 2px;
		padding: 0 2px;
	}

	.item-shortcut {
		flex-shrink: 0;
		padding: var(--space-0-5) var(--space-1-5);
		background: var(--bg-tertiary);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-sm);
		font-family: var(--font-mono);
		font-size: var(--text-2xs);
		color: var(--text-muted);
	}

	/* No results */
	.no-results {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		padding: var(--space-8);
		text-align: center;
	}

	.no-results-icon {
		width: 40px;
		height: 40px;
		display: flex;
		align-items: center;
		justify-content: center;
		background: var(--bg-tertiary);
		border-radius: var(--radius-full);
		font-size: var(--text-lg);
		color: var(--text-muted);
		margin-bottom: var(--space-3);
	}

	.no-results p {
		font-size: var(--text-sm);
		color: var(--text-muted);
	}

	/* Footer */
	.palette-footer {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: var(--space-6);
		padding: var(--space-3);
		border-top: 1px solid var(--border-subtle);
		background: var(--bg-tertiary);
	}

	.footer-hint {
		display: flex;
		align-items: center;
		gap: var(--space-1);
		font-size: var(--text-xs);
		color: var(--text-muted);
	}

	.footer-hint kbd {
		padding: var(--space-0-5) var(--space-1);
		background: var(--bg-secondary);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-sm);
		font-family: var(--font-mono);
		font-size: var(--text-2xs);
	}
</style>

// web-react/src/components/overlays/CommandPalette.tsx
/**
 * CommandPalette - Search and execute commands
 *
 * Features:
 * - Search input with fuzzy filtering
 * - Command sections (Tasks, Navigation, Environment, Settings, Projects, View)
 * - Keyboard navigation (↑/↓ to navigate, Enter to select, Escape to close)
 * - Search match highlighting
 */

import { useState, useEffect, useRef, useMemo, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { createPortal } from 'react-dom';
import { Icon } from '@/components/ui/Icon';
import { formatShortcut } from '@/lib/platform';
import './CommandPalette.css';

interface CommandPaletteProps {
	open: boolean;
	onClose: () => void;
}

interface Command {
	id: string;
	label: string;
	description?: string;
	icon: string;
	shortcut?: string;
	action: () => void;
	category: string;
}

function escapeRegex(str: string): string {
	return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function highlightMatch(text: string, query: string): React.ReactNode {
	if (!query.trim()) return text;
	const regex = new RegExp(`(${escapeRegex(query)})`, 'gi');
	const parts = text.split(regex);
	return parts.map((part, i) =>
		regex.test(part) ? <mark key={i}>{part}</mark> : part
	);
}

export function CommandPalette({ open, onClose }: CommandPaletteProps) {
	const navigate = useNavigate();
	const [searchQuery, setSearchQuery] = useState('');
	const [selectedIndex, setSelectedIndex] = useState(0);
	const inputRef = useRef<HTMLInputElement>(null);

	// Define commands
	const commands = useMemo<Command[]>(() => [
		// Tasks
		{
			id: 'new-task',
			label: 'New Task',
			description: 'Create a new task',
			icon: '+',
			shortcut: 'N',
			action: () => {
				onClose();
				window.dispatchEvent(new CustomEvent('orc:new-task'));
			},
			category: 'Tasks',
		},
		{
			id: 'go-tasks',
			label: 'Go to Tasks',
			description: 'View all tasks',
			icon: '■',
			action: () => {
				onClose();
				navigate('/');
			},
			category: 'Navigation',
		},
		{
			id: 'go-dashboard',
			label: 'Go to Dashboard',
			description: 'Overview and quick stats',
			icon: '■',
			action: () => {
				onClose();
				navigate('/dashboard');
			},
			category: 'Navigation',
		},
		// Environment
		{
			id: 'go-environment',
			label: 'Go to Environment',
			description: 'Claude ecosystem overview',
			icon: '⚙',
			action: () => {
				onClose();
				navigate('/environment');
			},
			category: 'Environment',
		},
		{
			id: 'go-skills',
			label: 'Go to Skills',
			description: 'Manage Claude skills',
			icon: '⚡',
			action: () => {
				onClose();
				navigate('/environment/claude/skills');
			},
			category: 'Environment',
		},
		{
			id: 'go-hooks',
			label: 'Go to Hooks',
			description: 'Configure event hooks',
			icon: '↻',
			action: () => {
				onClose();
				navigate('/environment/claude/hooks');
			},
			category: 'Environment',
		},
		{
			id: 'go-agents',
			label: 'Go to Agents',
			description: 'Sub-agent configurations',
			icon: '✦',
			action: () => {
				onClose();
				navigate('/environment/claude/agents');
			},
			category: 'Environment',
		},
		{
			id: 'go-tools',
			label: 'Go to Tools',
			description: 'Tool permissions',
			icon: '⚒',
			action: () => {
				onClose();
				navigate('/environment/claude/tools');
			},
			category: 'Environment',
		},
		{
			id: 'go-mcp',
			label: 'Go to MCP Servers',
			description: 'Manage MCP integrations',
			icon: '⊚',
			action: () => {
				onClose();
				navigate('/environment/claude/mcp');
			},
			category: 'Environment',
		},
		{
			id: 'go-prompts',
			label: 'Go to Prompts',
			description: 'Manage prompt templates',
			icon: '☰',
			action: () => {
				onClose();
				navigate('/environment/orchestrator/prompts');
			},
			category: 'Environment',
		},
		{
			id: 'go-scripts',
			label: 'Go to Scripts',
			description: 'Script registry',
			icon: '☰',
			action: () => {
				onClose();
				navigate('/environment/orchestrator/scripts');
			},
			category: 'Environment',
		},
		{
			id: 'go-automation',
			label: 'Go to Automation',
			description: 'Orc configuration',
			icon: '⚙',
			action: () => {
				onClose();
				navigate('/environment/orchestrator/automation');
			},
			category: 'Environment',
		},
		{
			id: 'go-export',
			label: 'Go to Export',
			description: 'Export configuration',
			icon: '⬆',
			action: () => {
				onClose();
				navigate('/environment/orchestrator/export');
			},
			category: 'Environment',
		},
		{
			id: 'go-knowledge',
			label: 'Go to Knowledge',
			description: 'Knowledge queue (patterns, gotchas, decisions)',
			icon: '📚',
			action: () => {
				onClose();
				navigate('/environment/knowledge');
			},
			category: 'Environment',
		},
		{
			id: 'go-docs',
			label: 'Go to Documentation',
			description: 'CLAUDE.md hierarchy',
			icon: '☰',
			action: () => {
				onClose();
				navigate('/environment/docs');
			},
			category: 'Environment',
		},
		{
			id: 'go-preferences',
			label: 'Go to Preferences',
			description: 'Personal and global settings',
			icon: '⚙',
			action: () => {
				onClose();
				navigate('/preferences');
			},
			category: 'Settings',
		},
		// Projects & View
		{
			id: 'switch-project',
			label: 'Switch Project',
			description: 'Change active project',
			icon: '⇄',
			shortcut: 'P',
			action: () => {
				onClose();
				window.dispatchEvent(new CustomEvent('orc:switch-project'));
			},
			category: 'Projects',
		},
		{
			id: 'toggle-sidebar',
			label: 'Toggle Sidebar',
			description: 'Show/hide navigation',
			icon: '☰',
			shortcut: 'B',
			action: () => {
				onClose();
				window.dispatchEvent(new CustomEvent('orc:toggle-sidebar'));
			},
			category: 'View',
		},
	], [onClose, navigate]);

	// Filter commands
	const filteredCommands = useMemo(() => {
		if (!searchQuery.trim()) return commands;
		const query = searchQuery.toLowerCase();
		return commands.filter(
			(cmd) =>
				cmd.label.toLowerCase().includes(query) ||
				cmd.description?.toLowerCase().includes(query) ||
				cmd.category.toLowerCase().includes(query)
		);
	}, [commands, searchQuery]);

	// Group by category
	const groupedCommands = useMemo(() => {
		const groups: Record<string, Command[]> = {};
		for (const cmd of filteredCommands) {
			if (!groups[cmd.category]) {
				groups[cmd.category] = [];
			}
			groups[cmd.category].push(cmd);
		}
		return groups;
	}, [filteredCommands]);

	// Reset state when modal opens
	useEffect(() => {
		if (open) {
			setSearchQuery('');
			setSelectedIndex(0);
			setTimeout(() => inputRef.current?.focus(), 50);
		}
	}, [open]);

	// Reset selected index when search changes
	useEffect(() => {
		setSelectedIndex(0);
	}, [searchQuery]);

	// Handle keyboard navigation
	const handleKeyDown = useCallback((e: React.KeyboardEvent) => {
		switch (e.key) {
			case 'ArrowDown':
				e.preventDefault();
				setSelectedIndex((prev) => Math.min(prev + 1, filteredCommands.length - 1));
				break;
			case 'ArrowUp':
				e.preventDefault();
				setSelectedIndex((prev) => Math.max(prev - 1, 0));
				break;
			case 'Enter':
				e.preventDefault();
				if (filteredCommands[selectedIndex]) {
					filteredCommands[selectedIndex].action();
				}
				break;
			case 'Escape':
				onClose();
				break;
		}
	}, [filteredCommands, selectedIndex, onClose]);

	// Handle backdrop click
	const handleBackdropClick = (e: React.MouseEvent) => {
		if (e.target === e.currentTarget) {
			onClose();
		}
	};

	if (!open) return null;

	const content = (
		<div
			className="palette-backdrop"
			role="dialog"
			aria-modal="true"
			aria-label="Command palette"
			onClick={handleBackdropClick}
			onKeyDown={handleKeyDown}
		>
			<div className="palette-content">
				{/* Search Input */}
				<div className="palette-search">
					<Icon name="search" size={16} className="search-icon" />
					<input
						ref={inputRef}
						type="text"
						value={searchQuery}
						onChange={(e) => setSearchQuery(e.target.value)}
						placeholder="Type a command or search..."
						className="search-input"
						aria-label="Search commands"
					/>
					<kbd className="search-hint">esc</kbd>
				</div>

				{/* Results */}
				<div className="palette-results">
					{Object.keys(groupedCommands).length > 0 ? (
						Object.entries(groupedCommands).map(([category, cmds]) => (
							<div key={category} className="result-group">
								<div className="group-label">{category}</div>
								{cmds.map((cmd) => {
									const globalIndex = filteredCommands.indexOf(cmd);
									return (
										<button
											key={cmd.id}
											className={`result-item ${globalIndex === selectedIndex ? 'selected' : ''}`}
											onClick={() => cmd.action()}
											onMouseEnter={() => setSelectedIndex(globalIndex)}
										>
											<span className="item-icon">{cmd.icon}</span>
											<div className="item-content">
												<span className="item-label">
													{highlightMatch(cmd.label, searchQuery)}
												</span>
												{cmd.description && (
													<span className="item-description">
														{highlightMatch(cmd.description, searchQuery)}
													</span>
												)}
											</div>
											{cmd.shortcut && (
												<kbd className="item-shortcut">
													{formatShortcut(cmd.shortcut)}
												</kbd>
											)}
										</button>
									);
								})}
							</div>
						))
					) : (
						<div className="no-results">
							<span className="no-results-icon">?</span>
							<p>No commands found</p>
						</div>
					)}
				</div>

				{/* Footer */}
				<div className="palette-footer">
					<div className="footer-hint">
						<kbd>↑</kbd><kbd>↓</kbd> to navigate
					</div>
					<div className="footer-hint">
						<kbd>↵</kbd> to select
					</div>
				</div>
			</div>
		</div>
	);

	return createPortal(content, document.body);
}
