// web-svelte-archive/src/lib/components/TaskCard.svelte
<script lang="ts">
	import type { Task } from '$lib/types';
	import StatusIndicator from './ui/StatusIndicator.svelte';
	import { getInitiativeBadgeTitle } from '$lib/stores/initiatives';

	interface Props {
		task: Task;
		compact?: boolean;
		onRun?: () => void;
		onPause?: () => void;
		onResume?: () => void;
		onDelete?: () => void;
		onTaskClick?: (task: Task) => void;
		onInitiativeClick?: (initiativeId: string) => void;
	}

	let { task, compact = false, onRun, onPause, onResume, onDelete, onTaskClick, onInitiativeClick }: Props = $props();

	const weightConfig: Record<string, { color: string; bg: string }> = {
		trivial: { color: 'var(--weight-trivial)', bg: 'rgba(107, 114, 128, 0.15)' },
		small: { color: 'var(--weight-small)', bg: 'var(--status-success-bg)' },
		medium: { color: 'var(--weight-medium)', bg: 'var(--status-info-bg)' },
		large: { color: 'var(--weight-large)', bg: 'var(--status-warning-bg)' },
		greenfield: { color: 'var(--weight-greenfield)', bg: 'var(--accent-subtle)' }
	};

	function formatDate(dateStr: string): string {
		const date = new Date(dateStr);
		const now = new Date();
		const diffMs = now.getTime() - date.getTime();
		const diffMins = Math.floor(diffMs / 60000);
		const diffHours = Math.floor(diffMins / 60);
		const diffDays = Math.floor(diffHours / 24);

		if (diffMins < 1) return 'just now';
		if (diffMins < 60) return `${diffMins}m ago`;
		if (diffHours < 24) return `${diffHours}h ago`;
		if (diffDays < 7) return `${diffDays}d ago`;
		return date.toLocaleDateString();
	}

	function handlePause(e: Event) {
		e.stopPropagation();
		e.preventDefault();
		onPause?.();
	}

	function handleRun(e: Event) {
		e.stopPropagation();
		e.preventDefault();
		onRun?.();
	}

	function handleDelete(e: Event) {
		e.stopPropagation();
		e.preventDefault();
		if (confirm(`Delete task ${task.id}?`)) {
			onDelete?.();
		}
	}

	function handleResume(e: Event) {
		e.stopPropagation();
		e.preventDefault();
		onResume?.();
	}

	const isRunning = $derived(task.status === 'running');
	const weight = $derived(weightConfig[task.weight] || weightConfig.small);
	const initiativeBadge = $derived(task.initiative_id ? getInitiativeBadgeTitle(task.initiative_id) : null);

	function handleInitiativeClick(e: MouseEvent) {
		e.stopPropagation();
		e.preventDefault();
		if (task.initiative_id && onInitiativeClick) {
			onInitiativeClick(task.initiative_id);
		}
	}

	function handleCardClick(e: MouseEvent) {
		// For running tasks, show transcript modal if callback provided
		if (task.status === 'running' && onTaskClick) {
			e.preventDefault();
			onTaskClick(task);
		}
	}
</script>

<a href="/tasks/{task.id}" class="task-card" class:running={isRunning} onclick={handleCardClick}>
	<!-- Left: Status Orb -->
	<div class="status-col">
		<StatusIndicator status={task.status} size="lg" />
	</div>

	<!-- Middle: Task Info -->
	<div class="task-info">
		<div class="task-header">
			<span class="task-id">{task.id}</span>
			{#if task.weight}
				<span
					class="weight-badge"
					style:color={weight.color}
					style:background={weight.bg}
				>
					{task.weight}
				</span>
			{/if}
			{#if task.is_blocked}
				<span
					class="blocked-badge"
					title="Blocked by {task.unmet_blockers?.join(', ')}"
				>
					<svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">
						<circle cx="12" cy="12" r="10" />
						<line x1="4.93" y1="4.93" x2="19.07" y2="19.07" />
					</svg>
					Blocked
				</span>
			{/if}
			{#if initiativeBadge}
				<button
					class="initiative-badge"
					onclick={handleInitiativeClick}
					title={initiativeBadge.full}
					type="button"
				>
					{initiativeBadge.display}
				</button>
			{/if}
		</div>
		<h3 class="task-title">{task.title}</h3>
		{#if task.current_phase}
			<div class="task-phase">
				<span class="phase-label">Phase:</span>
				<span class="phase-value">{task.current_phase}</span>
			</div>
		{/if}
	</div>

	<!-- Right: Meta & Actions -->
	<div class="task-right">
		<div class="task-meta">
			<span class="task-time">{formatDate(task.updated_at)}</span>
		</div>

		<div class="task-actions">
			{#if task.status === 'running' && onPause}
				<button class="action-btn" onclick={handlePause} title="Pause task">
					<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="currentColor" stroke="none">
						<rect x="6" y="4" width="4" height="16" rx="1" />
						<rect x="14" y="4" width="4" height="16" rx="1" />
					</svg>
					Pause
				</button>
			{:else if task.status === 'paused' && onResume}
				<button class="action-btn primary" onclick={handleResume} title="Resume task">
					<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="currentColor" stroke="none">
						<polygon points="5 3 19 12 5 21 5 3" />
					</svg>
					Resume
				</button>
			{:else if ['created', 'planned'].includes(task.status) && onRun}
				<button class="action-btn primary" onclick={handleRun} title="Run task">
					<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="currentColor" stroke="none">
						<polygon points="5 3 19 12 5 21 5 3" />
					</svg>
					Run
				</button>
			{/if}
			{#if task.status !== 'running' && onDelete}
				<button class="action-btn delete" onclick={handleDelete} title="Delete task">
					<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
						<polyline points="3 6 5 6 21 6" />
						<path d="M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6m3 0V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2" />
					</svg>
				</button>
			{/if}
		</div>
	</div>
</a>

<style>
	.task-card {
		display: flex;
		align-items: center;
		gap: var(--space-4);
		background: var(--bg-secondary);
		border: 1px solid var(--border-subtle);
		border-radius: var(--radius-lg);
		padding: var(--space-4);
		text-decoration: none;
		color: inherit;
		transition:
			border-color var(--duration-fast) var(--ease-out),
			box-shadow var(--duration-fast) var(--ease-out),
			transform var(--duration-fast) var(--ease-out);
	}

	.task-card:hover {
		border-color: var(--border-strong);
		transform: translateY(-1px);
		box-shadow: var(--shadow-md);
	}

	.task-card:focus-visible {
		outline: none;
		border-color: var(--accent-primary);
		box-shadow: 0 0 0 3px var(--accent-glow);
	}

	/* Running state animation */
	.task-card.running {
		animation: card-running-glow 2.5s ease-in-out infinite;
	}

	/* Status Column */
	.status-col {
		flex-shrink: 0;
		width: 24px;
		display: flex;
		justify-content: center;
	}

	/* Task Info */
	.task-info {
		flex: 1;
		min-width: 0;
	}

	.task-header {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		margin-bottom: var(--space-1);
	}

	.task-id {
		font-family: var(--font-mono);
		font-size: var(--text-xs);
		font-weight: var(--font-medium);
		color: var(--text-muted);
		letter-spacing: var(--tracking-wide);
	}

	.weight-badge {
		font-size: var(--text-2xs);
		font-weight: var(--font-semibold);
		text-transform: uppercase;
		letter-spacing: var(--tracking-wider);
		padding: var(--space-0-5) var(--space-1-5);
		border-radius: var(--radius-sm);
	}

	.blocked-badge {
		display: flex;
		align-items: center;
		gap: var(--space-1);
		font-size: var(--text-2xs);
		font-weight: var(--font-semibold);
		text-transform: uppercase;
		letter-spacing: var(--tracking-wider);
		padding: var(--space-0-5) var(--space-1-5);
		border-radius: var(--radius-sm);
		background: var(--status-danger-bg);
		color: var(--status-danger);
	}

	.initiative-badge {
		font-size: var(--text-2xs);
		font-weight: var(--font-medium);
		letter-spacing: var(--tracking-wide);
		padding: var(--space-0-5) var(--space-1-5);
		border-radius: var(--radius-sm);
		background: var(--bg-tertiary);
		color: var(--text-secondary);
		border: 1px solid var(--border-subtle);
		cursor: pointer;
		transition: all var(--duration-fast) var(--ease-out);
	}

	.initiative-badge:hover {
		background: var(--bg-surface);
		border-color: var(--border-default);
		color: var(--text-primary);
	}

	.task-title {
		font-size: var(--text-base);
		font-weight: var(--font-medium);
		color: var(--text-primary);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		margin: 0;
		letter-spacing: normal;
		text-transform: none;
	}

	.task-phase {
		display: flex;
		align-items: center;
		gap: var(--space-1);
		margin-top: var(--space-1);
		font-size: var(--text-xs);
	}

	.phase-label {
		color: var(--text-muted);
	}

	.phase-value {
		color: var(--accent-primary);
		font-weight: var(--font-medium);
	}

	/* Right Section */
	.task-right {
		display: flex;
		flex-direction: column;
		align-items: flex-end;
		gap: var(--space-2);
		flex-shrink: 0;
	}

	.task-meta {
		font-size: var(--text-xs);
		color: var(--text-muted);
	}

	.task-actions {
		display: flex;
		gap: var(--space-2);
		align-items: center;
	}

	/* Action Buttons */
	.action-btn {
		display: flex;
		align-items: center;
		gap: var(--space-1-5);
		padding: var(--space-1-5) var(--space-3);
		font-size: var(--text-xs);
		font-weight: var(--font-medium);
		background: var(--bg-tertiary);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-md);
		color: var(--text-secondary);
		cursor: pointer;
		transition: all var(--duration-fast) var(--ease-out);
	}

	.action-btn:hover {
		background: var(--bg-surface);
		color: var(--text-primary);
		border-color: var(--border-strong);
	}

	.action-btn.primary {
		background: var(--accent-primary);
		border-color: var(--accent-primary);
		color: var(--text-inverse);
	}

	.action-btn.primary:hover {
		background: var(--accent-hover);
		border-color: var(--accent-hover);
	}

	.action-btn.delete {
		padding: var(--space-1-5);
		background: transparent;
		border-color: transparent;
		color: var(--text-muted);
	}

	.action-btn.delete:hover {
		background: var(--status-danger-bg);
		border-color: var(--status-danger);
		color: var(--status-danger);
	}
</style>

// web-react/src/components/board/TaskCard.tsx
/**
 * TaskCard component for Kanban board
 *
 * Displays task information with:
 * - Status indicator, ID, and priority badge
 * - Title and description preview
 * - Phase indicator when running
 * - Weight badge, blocked indicator, initiative badge
 * - Action buttons (run/pause/resume/finalize)
 * - Quick menu for queue/priority changes
 * - Drag-and-drop support
 */

import { useState, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { StatusIndicator } from '@/components/ui/StatusIndicator';
import type { Task, TaskPriority, TaskQueue } from '@/lib/types';
import { PRIORITY_CONFIG } from '@/lib/types';
import { updateTask, triggerFinalize, type FinalizeState } from '@/lib/api';
import { useTaskStore, getInitiativeBadgeTitle } from '@/stores';
import './TaskCard.css';

interface TaskCardProps {
	task: Task;
	onAction: (taskId: string, action: 'run' | 'pause' | 'resume') => Promise<void>;
	onTaskClick?: (task: Task) => void;
	onInitiativeClick?: (initiativeId: string) => void;
	onFinalizeClick?: (task: Task) => void;
	finalizeState?: FinalizeState | null;
}

// Weight badge color config
const WEIGHT_CONFIG: Record<string, { color: string; bg: string }> = {
	trivial: { color: 'var(--weight-trivial)', bg: 'rgba(107, 114, 128, 0.15)' },
	small: { color: 'var(--weight-small)', bg: 'var(--status-success-bg)' },
	medium: { color: 'var(--weight-medium)', bg: 'var(--status-info-bg)' },
	large: { color: 'var(--weight-large)', bg: 'var(--status-warning-bg)' },
	greenfield: { color: 'var(--weight-greenfield)', bg: 'var(--accent-subtle)' },
};

function formatDate(dateStr: string): string {
	const date = new Date(dateStr);
	const now = new Date();
	const diffMs = now.getTime() - date.getTime();
	const diffMins = Math.floor(diffMs / 60000);
	const diffHours = Math.floor(diffMins / 60);
	const diffDays = Math.floor(diffHours / 24);

	if (diffMins < 1) return 'just now';
	if (diffMins < 60) return `${diffMins}m ago`;
	if (diffHours < 24) return `${diffHours}h ago`;
	if (diffDays < 7) return `${diffDays}d ago`;
	return date.toLocaleDateString();
}

export function TaskCard({
	task,
	onAction,
	onTaskClick,
	onInitiativeClick,
	onFinalizeClick,
	finalizeState,
}: TaskCardProps) {
	const navigate = useNavigate();
	const updateTaskInStore = useTaskStore((state) => state.updateTask);

	const [actionLoading, setActionLoading] = useState(false);
	const [isDragging, setIsDragging] = useState(false);
	const [showQuickMenu, setShowQuickMenu] = useState(false);
	const [quickMenuLoading, setQuickMenuLoading] = useState(false);
	const [finalizeLoading, setFinalizeLoading] = useState(false);

	// Derived values
	const priority = (task.priority || 'normal') as TaskPriority;
	const priorityConfig = PRIORITY_CONFIG[priority];
	const showPriority = priority !== 'normal';
	const queue = (task.queue || 'active') as TaskQueue;
	const weight = WEIGHT_CONFIG[task.weight] || WEIGHT_CONFIG.small;

	const isRunning = task.status === 'running';
	const isFinalizing = task.status === 'finalizing';
	const isFinished = task.status === 'finished';
	const isCompleted = task.status === 'completed';

	// Initiative badge
	const initiativeBadge = task.initiative_id ? getInitiativeBadgeTitle(task.initiative_id) : null;

	// Finalize progress
	const finalizeProgress =
		finalizeState && finalizeState.status !== 'not_started'
			? {
					step: finalizeState.step || 'Processing',
					progress: finalizeState.progress || '',
					percent: finalizeState.step_percent || 0,
				}
			: null;

	// Drag handlers
	const handleDragStart = useCallback(
		(e: React.DragEvent) => {
			e.dataTransfer.setData('application/json', JSON.stringify(task));
			e.dataTransfer.effectAllowed = 'move';
			setIsDragging(true);
		},
		[task]
	);

	const handleDragEnd = useCallback(() => {
		setIsDragging(false);
	}, []);

	// Action handler
	const handleAction = useCallback(
		async (action: 'run' | 'pause' | 'resume', e: React.MouseEvent) => {
			e.stopPropagation();
			e.preventDefault();
			setActionLoading(true);
			try {
				await onAction(task.id, action);
			} finally {
				setActionLoading(false);
			}
		},
		[task.id, onAction]
	);

	// Card click handler
	const openTask = useCallback(
		(e: React.MouseEvent) => {
			const target = e.target as HTMLElement;
			if (target.closest('.actions') || target.closest('.quick-menu')) {
				return;
			}
			// For running tasks, show transcript modal if callback provided
			if (task.status === 'running' && onTaskClick) {
				onTaskClick(task);
				return;
			}
			navigate(`/tasks/${task.id}`);
		},
		[task, onTaskClick, navigate]
	);

	// Keyboard handler
	const handleKeydown = useCallback(
		(e: React.KeyboardEvent) => {
			if (e.key === 'Enter' || e.key === ' ') {
				e.preventDefault();
				navigate(`/tasks/${task.id}`);
			}
			if (e.key === 'Escape' && showQuickMenu) {
				setShowQuickMenu(false);
			}
		},
		[task.id, showQuickMenu, navigate]
	);

	// Quick menu handlers
	const toggleQuickMenu = useCallback((e: React.MouseEvent) => {
		e.stopPropagation();
		e.preventDefault();
		setShowQuickMenu((prev) => !prev);
	}, []);

	const closeQuickMenu = useCallback(() => {
		setShowQuickMenu(false);
	}, []);

	const setQueueValue = useCallback(
		async (newQueue: TaskQueue) => {
			if (newQueue === queue) {
				setShowQuickMenu(false);
				return;
			}
			setQuickMenuLoading(true);
			try {
				const updated = await updateTask(task.id, { queue: newQueue });
				updateTaskInStore(task.id, updated);
			} catch (err) {
				console.error('Failed to update queue:', err);
			} finally {
				setQuickMenuLoading(false);
				setShowQuickMenu(false);
			}
		},
		[task.id, queue, updateTaskInStore]
	);

	const setPriorityValue = useCallback(
		async (newPriority: TaskPriority) => {
			if (newPriority === priority) {
				setShowQuickMenu(false);
				return;
			}
			setQuickMenuLoading(true);
			try {
				const updated = await updateTask(task.id, { priority: newPriority });
				updateTaskInStore(task.id, updated);
			} catch (err) {
				console.error('Failed to update priority:', err);
			} finally {
				setQuickMenuLoading(false);
				setShowQuickMenu(false);
			}
		},
		[task.id, priority, updateTaskInStore]
	);

	// Finalize handler
	const handleFinalize = useCallback(
		async (e: React.MouseEvent) => {
			e.stopPropagation();
			e.preventDefault();

			if (onFinalizeClick) {
				onFinalizeClick(task);
				return;
			}

			setFinalizeLoading(true);
			try {
				await triggerFinalize(task.id);
			} catch (err) {
				console.error('Failed to trigger finalize:', err);
			} finally {
				setFinalizeLoading(false);
			}
		},
		[task, onFinalizeClick]
	);

	// Initiative click handler
	const handleInitiativeClick = useCallback(
		(e: React.MouseEvent) => {
			e.stopPropagation();
			e.preventDefault();
			if (task.initiative_id && onInitiativeClick) {
				onInitiativeClick(task.initiative_id);
			}
		},
		[task.initiative_id, onInitiativeClick]
	);

	// Build class names
	const cardClasses = [
		'task-card',
		isDragging && 'dragging',
		isRunning && 'running',
		isFinalizing && 'finalizing',
		isFinished && 'finished',
		isCompleted && 'completed',
	]
		.filter(Boolean)
		.join(' ');

	return (
		<article
			className={cardClasses}
			draggable="true"
			onDragStart={handleDragStart}
			onDragEnd={handleDragEnd}
			onClick={openTask}
			onKeyDown={handleKeydown}
			tabIndex={0}
			aria-label={`Task ${task.id}: ${task.title}`}
		>
			<div className="card-header">
				<div className="header-left">
					<span className="task-id">{task.id}</span>
					{showPriority && (
						<span
							className={`priority-badge ${priority}`}
							style={{ color: priorityConfig.color }}
							title={`${priorityConfig.label} priority`}
						>
							{priority === 'critical' && (
								<svg
									xmlns="http://www.w3.org/2000/svg"
									width="10"
									height="10"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									strokeWidth="2.5"
									strokeLinecap="round"
									strokeLinejoin="round"
								>
									<circle cx="12" cy="12" r="10" />
									<line x1="12" y1="8" x2="12" y2="12" />
									<line x1="12" y1="16" x2="12.01" y2="16" />
								</svg>
							)}
							{priority === 'high' && (
								<svg
									xmlns="http://www.w3.org/2000/svg"
									width="10"
									height="10"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									strokeWidth="2.5"
									strokeLinecap="round"
									strokeLinejoin="round"
								>
									<polyline points="18 15 12 9 6 15" />
								</svg>
							)}
							{priority === 'low' && (
								<svg
									xmlns="http://www.w3.org/2000/svg"
									width="10"
									height="10"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									strokeWidth="2.5"
									strokeLinecap="round"
									strokeLinejoin="round"
								>
									<polyline points="6 9 12 15 18 9" />
								</svg>
							)}
						</span>
					)}
				</div>
				<StatusIndicator status={task.status} size="sm" />
			</div>

			<h3 className="task-title">{task.title}</h3>

			{task.description && <p className="task-description">{task.description}</p>}

			{task.current_phase && (
				<div className="task-phase">
					<span className="phase-label">Phase:</span>
					<span className="phase-value">{task.current_phase}</span>
				</div>
			)}

			{/* Finalize progress indicator */}
			{isFinalizing && finalizeProgress && (
				<div className="finalize-progress">
					<div className="finalize-step">{finalizeProgress.step}</div>
					<div className="progress-bar">
						<div
							className="progress-fill"
							style={{ width: `${finalizeProgress.percent}%` }}
						/>
					</div>
				</div>
			)}

			{/* Finished commit info */}
			{isFinished && finalizeState?.result?.commit_sha && (
				<div className="finished-info">
					<svg
						xmlns="http://www.w3.org/2000/svg"
						width="12"
						height="12"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						strokeWidth="2"
						strokeLinecap="round"
						strokeLinejoin="round"
					>
						<circle cx="12" cy="12" r="4" />
						<line x1="1.05" y1="12" x2="7" y2="12" />
						<line x1="17.01" y1="12" x2="22.96" y2="12" />
					</svg>
					<span className="commit-sha">
						{finalizeState.result.commit_sha.slice(0, 7)}
					</span>
					<span className="merge-target">
						merged to {finalizeState.result.target_branch}
					</span>
				</div>
			)}

			<div className="card-footer">
				<div className="footer-left">
					<span
						className="weight-badge"
						style={{ color: weight.color, background: weight.bg }}
					>
						{task.weight}
					</span>
					{task.is_blocked && (
						<span
							className="blocked-badge"
							title={`Blocked by ${task.unmet_blockers?.join(', ')}`}
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="10"
								height="10"
								viewBox="0 0 24 24"
								fill="none"
								stroke="currentColor"
								strokeWidth="2.5"
								strokeLinecap="round"
								strokeLinejoin="round"
							>
								<circle cx="12" cy="12" r="10" />
								<line x1="4.93" y1="4.93" x2="19.07" y2="19.07" />
							</svg>
							Blocked
						</span>
					)}
					{initiativeBadge && (
						<button
							className="initiative-badge"
							onClick={handleInitiativeClick}
							title={initiativeBadge.full}
							type="button"
						>
							{initiativeBadge.display}
						</button>
					)}
					<span className="updated-time">{formatDate(task.updated_at)}</span>
				</div>

				<div className="actions">
					{(task.status === 'created' || task.status === 'planned') && (
						<button
							className="action-btn run"
							onClick={(e) => handleAction('run', e)}
							disabled={actionLoading}
							title="Run task"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="12"
								height="12"
								viewBox="0 0 24 24"
								fill="currentColor"
								stroke="none"
							>
								<polygon points="5 3 19 12 5 21 5 3" />
							</svg>
						</button>
					)}
					{task.status === 'running' && (
						<button
							className="action-btn pause"
							onClick={(e) => handleAction('pause', e)}
							disabled={actionLoading}
							title="Pause task"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="12"
								height="12"
								viewBox="0 0 24 24"
								fill="currentColor"
								stroke="none"
							>
								<rect x="6" y="4" width="4" height="16" rx="1" />
								<rect x="14" y="4" width="4" height="16" rx="1" />
							</svg>
						</button>
					)}
					{task.status === 'paused' && (
						<button
							className="action-btn resume"
							onClick={(e) => handleAction('resume', e)}
							disabled={actionLoading}
							title="Resume task"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="12"
								height="12"
								viewBox="0 0 24 24"
								fill="currentColor"
								stroke="none"
							>
								<polygon points="5 3 19 12 5 21 5 3" />
							</svg>
						</button>
					)}
					{task.status === 'completed' && (
						<button
							className="action-btn finalize"
							onClick={handleFinalize}
							disabled={finalizeLoading}
							title="Finalize and merge"
						>
							{finalizeLoading ? (
								<div className="btn-spinner" />
							) : (
								<svg
									xmlns="http://www.w3.org/2000/svg"
									width="12"
									height="12"
									viewBox="0 0 24 24"
									fill="none"
									stroke="currentColor"
									strokeWidth="2"
									strokeLinecap="round"
									strokeLinejoin="round"
								>
									<circle cx="18" cy="18" r="3" />
									<circle cx="6" cy="6" r="3" />
									<path d="M6 21V9a9 9 0 0 0 9 9" />
								</svg>
							)}
						</button>
					)}

					{/* Quick menu for queue/priority */}
					<div className="quick-menu">
						<button
							className="action-btn more"
							onClick={toggleQuickMenu}
							title="Quick actions"
							aria-expanded={showQuickMenu}
							aria-haspopup="true"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								width="12"
								height="12"
								viewBox="0 0 24 24"
								fill="currentColor"
								stroke="none"
							>
								<circle cx="12" cy="5" r="2" />
								<circle cx="12" cy="12" r="2" />
								<circle cx="12" cy="19" r="2" />
							</svg>
						</button>

						{showQuickMenu && (
							<>
								<div
									className="quick-menu-backdrop"
									onClick={closeQuickMenu}
									onKeyDown={(e) => e.key === 'Escape' && closeQuickMenu()}
								/>
								<div className="quick-menu-dropdown" role="menu">
									{quickMenuLoading ? (
										<div className="menu-loading">
											<div className="spinner" />
										</div>
									) : (
										<>
											{/* Queue section */}
											<div className="menu-section">
												<div className="menu-label">Queue</div>
												<button
													className={`menu-item ${queue === 'active' ? 'selected' : ''}`}
													onClick={() => setQueueValue('active')}
													role="menuitem"
												>
													<span className="menu-icon active-icon" />
													Active
												</button>
												<button
													className={`menu-item ${queue === 'backlog' ? 'selected' : ''}`}
													onClick={() => setQueueValue('backlog')}
													role="menuitem"
												>
													<span className="menu-icon backlog-icon" />
													Backlog
												</button>
											</div>

											<div className="menu-divider" />

											{/* Priority section */}
											<div className="menu-section">
												<div className="menu-label">Priority</div>
												<button
													className={`menu-item ${priority === 'critical' ? 'selected' : ''}`}
													onClick={() => setPriorityValue('critical')}
													role="menuitem"
												>
													<span
														className="menu-icon priority-icon"
														style={{
															background: 'var(--status-error)',
														}}
													/>
													Critical
												</button>
												<button
													className={`menu-item ${priority === 'high' ? 'selected' : ''}`}
													onClick={() => setPriorityValue('high')}
													role="menuitem"
												>
													<span
														className="menu-icon priority-icon"
														style={{
															background: 'var(--status-warning)',
														}}
													/>
													High
												</button>
												<button
													className={`menu-item ${priority === 'normal' ? 'selected' : ''}`}
													onClick={() => setPriorityValue('normal')}
													role="menuitem"
												>
													<span
														className="menu-icon priority-icon"
														style={{
															background: 'var(--text-muted)',
														}}
													/>
													Normal
												</button>
												<button
													className={`menu-item ${priority === 'low' ? 'selected' : ''}`}
													onClick={() => setPriorityValue('low')}
													role="menuitem"
												>
													<span
														className="menu-icon priority-icon"
														style={{
															background: 'var(--text-disabled)',
														}}
													/>
													Low
												</button>
											</div>
										</>
									)}
								</div>
							</>
						)}
					</div>
				</div>
			</div>
		</article>
	);
}
