// web/src/pages/environment/Config.tsx
/**
 * Config page (/environment/config)
 * Displays and edits orc configuration from .orc/config.yaml
 */

import { useState, useEffect, useCallback } from 'react';
import * as Accordion from '@radix-ui/react-accordion';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Icon } from '@/components/ui/Icon';
import { toast } from '@/stores';
import {
	getConfig,
	updateConfig,
	type Config as ConfigType,
	type ConfigUpdateRequest,
} from '@/lib/api';
import './environment.css';

export function Config() {
	const [config, setConfig] = useState<ConfigType | null>(null);
	const [loading, setLoading] = useState(true);
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const [hasChanges, setHasChanges] = useState(false);

	// Form state mirrors config structure
	const [formData, setFormData] = useState<ConfigUpdateRequest>({});

	const loadConfig = useCallback(async () => {
		try {
			setLoading(true);
			setError(null);
			const data = await getConfig();
			setConfig(data);
			// Initialize form with current values
			setFormData({
				profile: data.profile,
				automation: { ...data.automation },
				execution: { ...data.execution },
				git: { ...data.git },
				worktree: { ...data.worktree },
				completion: { ...data.completion },
				timeouts: { ...data.timeouts },
			});
		} catch (err) {
			setError(err instanceof Error ? err.message : 'Failed to load configuration');
		} finally {
			setLoading(false);
		}
	}, []);

	useEffect(() => {
		loadConfig();
	}, [loadConfig]);

	const handleChange = <K extends keyof ConfigUpdateRequest>(
		section: K,
		field: keyof NonNullable<ConfigUpdateRequest[K]>,
		value: unknown
	) => {
		setFormData((prev) => ({
			...prev,
			[section]: {
				...(prev[section] as object),
				[field]: value,
			},
		}));
		setHasChanges(true);
	};

	const handleProfileChange = (value: string) => {
		setFormData((prev) => ({ ...prev, profile: value }));
		setHasChanges(true);
	};

	const handleSave = async () => {
		try {
			setSaving(true);
			await updateConfig(formData);
			toast.success('Configuration saved');
			setHasChanges(false);
			await loadConfig();
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to save configuration');
		} finally {
			setSaving(false);
		}
	};

	const handleReset = () => {
		if (!config) return;
		setFormData({
			profile: config.profile,
			automation: { ...config.automation },
			execution: { ...config.execution },
			git: { ...config.git },
			worktree: { ...config.worktree },
			completion: { ...config.completion },
			timeouts: { ...config.timeouts },
		});
		setHasChanges(false);
	};

	if (loading) {
		return (
			<div className="page environment-config-page">
				<div className="env-loading">Loading configuration...</div>
			</div>
		);
	}

	if (error) {
		return (
			<div className="page environment-config-page">
				<div className="env-error">
					<p>{error}</p>
					<Button variant="secondary" onClick={loadConfig}>
						Retry
					</Button>
				</div>
			</div>
		);
	}

	return (
		<div className="page environment-config-page">
			<div className="env-page-header">
				<h3>Orc Configuration</h3>
				<div className="env-page-header-actions">
					{hasChanges && (
						<>
							<Button variant="ghost" onClick={handleReset}>
								Reset
							</Button>
							<Button variant="primary" onClick={handleSave} loading={saving}>
								Save Changes
							</Button>
						</>
					)}
				</div>
			</div>

			<Accordion.Root type="multiple" defaultValue={['automation', 'execution']} className="config-accordion">
				{/* Profile */}
				<Accordion.Item value="profile" className="config-section">
					<Accordion.Header>
						<Accordion.Trigger className="config-section-header">
							<h4 className="config-section-title">
								<Icon name="zap" size={18} />
								Profile
							</h4>
							<Icon name="chevron-down" size={16} />
						</Accordion.Trigger>
					</Accordion.Header>
					<Accordion.Content className="config-section-content">
						<div className="config-field">
							<label htmlFor="profile">Automation Profile</label>
							<select
								id="profile"
								value={formData.profile || ''}
								onChange={(e) => handleProfileChange(e.target.value)}
								className="input-field"
								style={{ padding: 'var(--space-2)' }}
							>
								<option value="auto">Auto (fully automated)</option>
								<option value="fast">Fast (speed over safety)</option>
								<option value="safe">Safe (AI reviews, human merge)</option>
								<option value="strict">Strict (human gates)</option>
							</select>
						</div>
					</Accordion.Content>
				</Accordion.Item>

				{/* Automation */}
				<Accordion.Item value="automation" className="config-section">
					<Accordion.Header>
						<Accordion.Trigger className="config-section-header">
							<h4 className="config-section-title">
								<Icon name="target" size={18} />
								Automation
							</h4>
							<Icon name="chevron-down" size={16} />
						</Accordion.Trigger>
					</Accordion.Header>
					<Accordion.Content className="config-section-content">
						<div className="config-field-group">
							<div className="config-field">
								<label htmlFor="gates_default">Gates Default</label>
								<select
									id="gates_default"
									value={formData.automation?.gates_default || ''}
									onChange={(e) => handleChange('automation', 'gates_default', e.target.value)}
									className="input-field"
									style={{ padding: 'var(--space-2)' }}
								>
									<option value="ai">AI</option>
									<option value="human">Human</option>
									<option value="auto">Auto</option>
								</select>
							</div>
							<div className="config-field config-checkbox-field">
								<input
									type="checkbox"
									id="retry_enabled"
									checked={formData.automation?.retry_enabled ?? false}
									onChange={(e) => handleChange('automation', 'retry_enabled', e.target.checked)}
								/>
								<label htmlFor="retry_enabled">Retry Enabled</label>
							</div>
							<div className="config-field">
								<label htmlFor="retry_max">Max Retries</label>
								<Input
									id="retry_max"
									type="number"
									min="0"
									max="10"
									value={formData.automation?.retry_max ?? ''}
									onChange={(e) => handleChange('automation', 'retry_max', parseInt(e.target.value) || 0)}
									size="sm"
								/>
							</div>
						</div>
					</Accordion.Content>
				</Accordion.Item>

				{/* Execution */}
				<Accordion.Item value="execution" className="config-section">
					<Accordion.Header>
						<Accordion.Trigger className="config-section-header">
							<h4 className="config-section-title">
								<Icon name="cpu" size={18} />
								Execution
							</h4>
							<Icon name="chevron-down" size={16} />
						</Accordion.Trigger>
					</Accordion.Header>
					<Accordion.Content className="config-section-content">
						<div className="config-field-group">
							<div className="config-field">
								<label htmlFor="model">Model</label>
								<Input
									id="model"
									value={formData.execution?.model ?? ''}
									onChange={(e) => handleChange('execution', 'model', e.target.value)}
									size="sm"
									placeholder="claude-sonnet-4-20250514"
								/>
							</div>
							<div className="config-field">
								<label htmlFor="max_iterations">Max Iterations</label>
								<Input
									id="max_iterations"
									type="number"
									min="1"
									max="100"
									value={formData.execution?.max_iterations ?? ''}
									onChange={(e) => handleChange('execution', 'max_iterations', parseInt(e.target.value) || 10)}
									size="sm"
								/>
							</div>
							<div className="config-field">
								<label htmlFor="timeout">Timeout</label>
								<Input
									id="timeout"
									value={formData.execution?.timeout ?? ''}
									onChange={(e) => handleChange('execution', 'timeout', e.target.value)}
									size="sm"
									placeholder="30m"
								/>
							</div>
						</div>
					</Accordion.Content>
				</Accordion.Item>

				{/* Git */}
				<Accordion.Item value="git" className="config-section">
					<Accordion.Header>
						<Accordion.Trigger className="config-section-header">
							<h4 className="config-section-title">
								<Icon name="git-branch" size={18} />
								Git
							</h4>
							<Icon name="chevron-down" size={16} />
						</Accordion.Trigger>
					</Accordion.Header>
					<Accordion.Content className="config-section-content">
						<div className="config-field-group">
							<div className="config-field">
								<label htmlFor="branch_prefix">Branch Prefix</label>
								<Input
									id="branch_prefix"
									value={formData.git?.branch_prefix ?? ''}
									onChange={(e) => handleChange('git', 'branch_prefix', e.target.value)}
									size="sm"
									placeholder="orc/"
								/>
							</div>
							<div className="config-field">
								<label htmlFor="commit_prefix">Commit Prefix</label>
								<Input
									id="commit_prefix"
									value={formData.git?.commit_prefix ?? ''}
									onChange={(e) => handleChange('git', 'commit_prefix', e.target.value)}
									size="sm"
									placeholder="[orc]"
								/>
							</div>
						</div>
					</Accordion.Content>
				</Accordion.Item>

				{/* Worktree */}
				<Accordion.Item value="worktree" className="config-section">
					<Accordion.Header>
						<Accordion.Trigger className="config-section-header">
							<h4 className="config-section-title">
								<Icon name="folder" size={18} />
								Worktree
							</h4>
							<Icon name="chevron-down" size={16} />
						</Accordion.Trigger>
					</Accordion.Header>
					<Accordion.Content className="config-section-content">
						<div className="config-field-group">
							<div className="config-field config-checkbox-field">
								<input
									type="checkbox"
									id="worktree_enabled"
									checked={formData.worktree?.enabled ?? false}
									onChange={(e) => handleChange('worktree', 'enabled', e.target.checked)}
								/>
								<label htmlFor="worktree_enabled">Enabled</label>
							</div>
							<div className="config-field">
								<label htmlFor="worktree_dir">Directory</label>
								<Input
									id="worktree_dir"
									value={formData.worktree?.dir ?? ''}
									onChange={(e) => handleChange('worktree', 'dir', e.target.value)}
									size="sm"
									placeholder=".orc/worktrees"
								/>
							</div>
							<div className="config-field config-checkbox-field">
								<input
									type="checkbox"
									id="cleanup_on_complete"
									checked={formData.worktree?.cleanup_on_complete ?? false}
									onChange={(e) => handleChange('worktree', 'cleanup_on_complete', e.target.checked)}
								/>
								<label htmlFor="cleanup_on_complete">Cleanup on Complete</label>
							</div>
							<div className="config-field config-checkbox-field">
								<input
									type="checkbox"
									id="cleanup_on_fail"
									checked={formData.worktree?.cleanup_on_fail ?? false}
									onChange={(e) => handleChange('worktree', 'cleanup_on_fail', e.target.checked)}
								/>
								<label htmlFor="cleanup_on_fail">Cleanup on Fail</label>
							</div>
						</div>
					</Accordion.Content>
				</Accordion.Item>

				{/* Completion */}
				<Accordion.Item value="completion" className="config-section">
					<Accordion.Header>
						<Accordion.Trigger className="config-section-header">
							<h4 className="config-section-title">
								<Icon name="check-circle" size={18} />
								Completion
							</h4>
							<Icon name="chevron-down" size={16} />
						</Accordion.Trigger>
					</Accordion.Header>
					<Accordion.Content className="config-section-content">
						<div className="config-field-group">
							<div className="config-field">
								<label htmlFor="completion_action">Action</label>
								<select
									id="completion_action"
									value={formData.completion?.action || ''}
									onChange={(e) => handleChange('completion', 'action', e.target.value)}
									className="input-field"
									style={{ padding: 'var(--space-2)' }}
								>
									<option value="pr">Create PR</option>
									<option value="merge">Merge</option>
									<option value="none">None</option>
								</select>
							</div>
							<div className="config-field">
								<label htmlFor="target_branch">Target Branch</label>
								<Input
									id="target_branch"
									value={formData.completion?.target_branch ?? ''}
									onChange={(e) => handleChange('completion', 'target_branch', e.target.value)}
									size="sm"
									placeholder="main"
								/>
							</div>
							<div className="config-field config-checkbox-field">
								<input
									type="checkbox"
									id="delete_branch"
									checked={formData.completion?.delete_branch ?? false}
									onChange={(e) => handleChange('completion', 'delete_branch', e.target.checked)}
								/>
								<label htmlFor="delete_branch">Delete Branch After Merge</label>
							</div>
						</div>
					</Accordion.Content>
				</Accordion.Item>

				{/* Timeouts */}
				<Accordion.Item value="timeouts" className="config-section">
					<Accordion.Header>
						<Accordion.Trigger className="config-section-header">
							<h4 className="config-section-title">
								<Icon name="clock" size={18} />
								Timeouts
							</h4>
							<Icon name="chevron-down" size={16} />
						</Accordion.Trigger>
					</Accordion.Header>
					<Accordion.Content className="config-section-content">
						<div className="config-field-group">
							<div className="config-field">
								<label htmlFor="phase_max">Phase Max</label>
								<Input
									id="phase_max"
									value={formData.timeouts?.phase_max ?? ''}
									onChange={(e) => handleChange('timeouts', 'phase_max', e.target.value)}
									size="sm"
									placeholder="1h"
								/>
							</div>
							<div className="config-field">
								<label htmlFor="turn_max">Turn Max</label>
								<Input
									id="turn_max"
									value={formData.timeouts?.turn_max ?? ''}
									onChange={(e) => handleChange('timeouts', 'turn_max', e.target.value)}
									size="sm"
									placeholder="5m"
								/>
							</div>
							<div className="config-field">
								<label htmlFor="idle_warning">Idle Warning</label>
								<Input
									id="idle_warning"
									value={formData.timeouts?.idle_warning ?? ''}
									onChange={(e) => handleChange('timeouts', 'idle_warning', e.target.value)}
									size="sm"
									placeholder="2m"
								/>
							</div>
							<div className="config-field">
								<label htmlFor="heartbeat_interval">Heartbeat Interval</label>
								<Input
									id="heartbeat_interval"
									value={formData.timeouts?.heartbeat_interval ?? ''}
									onChange={(e) => handleChange('timeouts', 'heartbeat_interval', e.target.value)}
									size="sm"
									placeholder="10s"
								/>
							</div>
							<div className="config-field">
								<label htmlFor="idle_timeout">Idle Timeout</label>
								<Input
									id="idle_timeout"
									value={formData.timeouts?.idle_timeout ?? ''}
									onChange={(e) => handleChange('timeouts', 'idle_timeout', e.target.value)}
									size="sm"
									placeholder="10m"
								/>
							</div>
						</div>
					</Accordion.Content>
				</Accordion.Item>
			</Accordion.Root>
		</div>
	);
}

// web/src/routes/config/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getConfig, updateConfig, type Config, type ConfigUpdateRequest } from '$lib/api';

	let config = $state<Config | null>(null);
	let loading = $state(true);
	let saving = $state(false);
	let error = $state<string | null>(null);
	let success = $state<string | null>(null);
	let editing = $state(false);

	// Edit form state
	let editProfile = $state('');
	let editGatesDefault = $state('');
	let editRetryEnabled = $state(false);
	let editRetryMax = $state(3);
	let editModel = $state('');
	let editMaxIterations = $state(10);
	let editTimeout = $state('');
	let editBranchPrefix = $state('');
	let editCommitPrefix = $state('');

	const profiles = ['auto', 'fast', 'safe', 'strict'];
	const gateTypes = ['auto', 'human', 'ai'];

	onMount(async () => {
		await loadConfig();
	});

	async function loadConfig() {
		loading = true;
		error = null;
		try {
			config = await getConfig();
			resetEditForm();
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load config';
		} finally {
			loading = false;
		}
	}

	function resetEditForm() {
		if (!config) return;
		editProfile = config.profile;
		editGatesDefault = config.automation.gates_default;
		editRetryEnabled = config.automation.retry_enabled;
		editRetryMax = config.automation.retry_max;
		editModel = config.execution.model;
		editMaxIterations = config.execution.max_iterations;
		editTimeout = config.execution.timeout;
		editBranchPrefix = config.git.branch_prefix;
		editCommitPrefix = config.git.commit_prefix;
	}

	function startEdit() {
		resetEditForm();
		editing = true;
		success = null;
	}

	function cancelEdit() {
		editing = false;
		resetEditForm();
	}

	async function saveConfig() {
		saving = true;
		error = null;
		success = null;

		try {
			const req: ConfigUpdateRequest = {
				profile: editProfile,
				automation: {
					gates_default: editGatesDefault,
					retry_enabled: editRetryEnabled,
					retry_max: editRetryMax
				},
				execution: {
					model: editModel,
					max_iterations: editMaxIterations,
					timeout: editTimeout
				},
				git: {
					branch_prefix: editBranchPrefix,
					commit_prefix: editCommitPrefix
				}
			};

			config = await updateConfig(req);
			editing = false;
			success = 'Configuration saved successfully';
			setTimeout(() => success = null, 3000);
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to save config';
		} finally {
			saving = false;
		}
	}
</script>

<svelte:head>
	<title>Config - orc</title>
</svelte:head>

<div class="page">
	<header class="page-header">
		<h1>Configuration</h1>
		{#if !editing && config}
			<button class="primary" onclick={startEdit}>Edit</button>
		{/if}
	</header>

	{#if success}
		<div class="success-banner">{success}</div>
	{/if}

	{#if error}
		<div class="error-banner">
			{error}
			<button onclick={() => error = null}>Dismiss</button>
		</div>
	{/if}

	{#if loading}
		<div class="loading">Loading configuration...</div>
	{:else if config}
		{#if editing}
			<!-- Edit Mode -->
			<form class="config-form" onsubmit={(e) => { e.preventDefault(); saveConfig(); }}>
				<section class="config-section">
					<h2>Automation</h2>
					<div class="form-group">
						<label for="profile">Profile</label>
						<select id="profile" bind:value={editProfile}>
							{#each profiles as p}
								<option value={p}>{p}</option>
							{/each}
						</select>
						<span class="hint">Controls overall automation level</span>
					</div>
					<div class="form-group">
						<label for="gates_default">Default Gate</label>
						<select id="gates_default" bind:value={editGatesDefault}>
							{#each gateTypes as g}
								<option value={g}>{g}</option>
							{/each}
						</select>
						<span class="hint">Gate type for phase transitions</span>
					</div>
					<div class="form-group checkbox">
						<input type="checkbox" id="retry_enabled" bind:checked={editRetryEnabled} />
						<label for="retry_enabled">Enable Retry</label>
						<span class="hint">Automatically retry failed phases</span>
					</div>
					<div class="form-group">
						<label for="retry_max">Max Retries</label>
						<input type="number" id="retry_max" bind:value={editRetryMax} min="0" max="10" />
						<span class="hint">Maximum retry attempts (0-10)</span>
					</div>
				</section>

				<section class="config-section">
					<h2>Execution</h2>
					<div class="form-group">
						<label for="model">Model</label>
						<input type="text" id="model" bind:value={editModel} placeholder="claude-sonnet-4-20250514" />
						<span class="hint">Claude model for execution</span>
					</div>
					<div class="form-group">
						<label for="max_iterations">Max Iterations</label>
						<input type="number" id="max_iterations" bind:value={editMaxIterations} min="1" max="100" />
						<span class="hint">Max iterations per phase (1-100)</span>
					</div>
					<div class="form-group">
						<label for="timeout">Timeout</label>
						<input type="text" id="timeout" bind:value={editTimeout} placeholder="30m" />
						<span class="hint">Task timeout (e.g., 30m, 1h)</span>
					</div>
				</section>

				<section class="config-section">
					<h2>Git</h2>
					<div class="form-group">
						<label for="branch_prefix">Branch Prefix</label>
						<input type="text" id="branch_prefix" bind:value={editBranchPrefix} placeholder="orc/" />
						<span class="hint">Prefix for task branches</span>
					</div>
					<div class="form-group">
						<label for="commit_prefix">Commit Prefix</label>
						<input type="text" id="commit_prefix" bind:value={editCommitPrefix} placeholder="[orc]" />
						<span class="hint">Prefix for commit messages</span>
					</div>
				</section>

				<div class="form-actions">
					<button type="button" onclick={cancelEdit} disabled={saving}>Cancel</button>
					<button type="submit" class="primary" disabled={saving}>
						{saving ? 'Saving...' : 'Save Changes'}
					</button>
				</div>
			</form>
		{:else}
			<!-- View Mode -->
			<div class="config-sections">
				<section class="config-section">
					<h2>Automation</h2>
					<table class="config-table">
						<tbody>
							<tr>
								<td class="label">Profile</td>
								<td class="value">{config.automation.profile}</td>
							</tr>
							<tr>
								<td class="label">Default Gate</td>
								<td class="value">{config.automation.gates_default}</td>
							</tr>
							<tr>
								<td class="label">Retry Enabled</td>
								<td class="value">{config.automation.retry_enabled ? 'Yes' : 'No'}</td>
							</tr>
							<tr>
								<td class="label">Max Retries</td>
								<td class="value">{config.automation.retry_max}</td>
							</tr>
						</tbody>
					</table>
				</section>

				<section class="config-section">
					<h2>Execution</h2>
					<table class="config-table">
						<tbody>
							<tr>
								<td class="label">Model</td>
								<td class="value mono">{config.execution.model}</td>
							</tr>
							<tr>
								<td class="label">Max Iterations</td>
								<td class="value">{config.execution.max_iterations}</td>
							</tr>
							<tr>
								<td class="label">Timeout</td>
								<td class="value">{config.execution.timeout}</td>
							</tr>
						</tbody>
					</table>
				</section>

				<section class="config-section">
					<h2>Git</h2>
					<table class="config-table">
						<tbody>
							<tr>
								<td class="label">Branch Prefix</td>
								<td class="value mono">{config.git.branch_prefix}</td>
							</tr>
							<tr>
								<td class="label">Commit Prefix</td>
								<td class="value mono">{config.git.commit_prefix}</td>
							</tr>
						</tbody>
					</table>
				</section>

				<section class="config-section">
					<h2>Version</h2>
					<p class="version">{config.version}</p>
				</section>
			</div>
		{/if}
	{/if}
</div>

<style>
	.page {
		max-width: 700px;
	}

	.page-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 2rem;
	}

	h1 {
		font-size: 1.5rem;
		font-weight: 600;
	}

	.config-sections, .config-form {
		display: flex;
		flex-direction: column;
		gap: 2rem;
	}

	.config-section {
		background: var(--bg-secondary);
		border: 1px solid var(--border-color);
		border-radius: 8px;
		padding: 1.25rem;
	}

	.config-section h2 {
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-secondary);
		text-transform: uppercase;
		letter-spacing: 0.05em;
		margin-bottom: 1rem;
	}

	.config-table {
		width: 100%;
		border-collapse: collapse;
	}

	.config-table tr {
		border-bottom: 1px solid var(--border-color);
	}

	.config-table tr:last-child {
		border-bottom: none;
	}

	.config-table td {
		padding: 0.75rem 0;
	}

	.config-table .label {
		color: var(--text-secondary);
		font-size: 0.875rem;
		width: 40%;
	}

	.config-table .value {
		color: var(--text-primary);
		font-weight: 500;
	}

	.config-table .value.mono {
		font-family: var(--font-mono);
		font-size: 0.875rem;
	}

	.version {
		font-family: var(--font-mono);
		font-size: 0.875rem;
		color: var(--text-secondary);
	}

	/* Form styles */
	.form-group {
		margin-bottom: 1rem;
	}

	.form-group:last-child {
		margin-bottom: 0;
	}

	.form-group label {
		display: block;
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-primary);
		margin-bottom: 0.375rem;
	}

	.form-group.checkbox {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.form-group.checkbox label {
		display: inline;
		margin-bottom: 0;
	}

	.form-group.checkbox .hint {
		flex: 1;
	}

	.form-group input[type="text"],
	.form-group input[type="number"],
	.form-group select {
		width: 100%;
		padding: 0.625rem 0.75rem;
		background: var(--bg-tertiary);
		border: 1px solid var(--border-color);
		border-radius: 6px;
		color: var(--text-primary);
		font-size: 0.875rem;
	}

	.form-group input:focus,
	.form-group select:focus {
		outline: none;
		border-color: var(--accent-primary);
	}

	.form-group input[type="checkbox"] {
		width: 1rem;
		height: 1rem;
		accent-color: var(--accent-primary);
	}

	.form-group .hint {
		display: block;
		font-size: 0.75rem;
		color: var(--text-muted);
		margin-top: 0.25rem;
	}

	.form-actions {
		display: flex;
		justify-content: flex-end;
		gap: 0.75rem;
	}

	.success-banner {
		background: rgba(63, 185, 80, 0.1);
		border: 1px solid var(--accent-success);
		border-radius: 6px;
		padding: 0.75rem 1rem;
		margin-bottom: 1rem;
		color: var(--accent-success);
	}

	.error-banner {
		background: rgba(248, 81, 73, 0.1);
		border: 1px solid var(--accent-danger);
		border-radius: 6px;
		padding: 0.75rem 1rem;
		margin-bottom: 1rem;
		display: flex;
		justify-content: space-between;
		align-items: center;
		color: var(--accent-danger);
	}

	.error-banner button {
		background: transparent;
		border: none;
		color: var(--accent-danger);
		padding: 0.25rem 0.5rem;
	}

	.loading {
		text-align: center;
		padding: 3rem;
		color: var(--text-secondary);
	}
</style>
