// web-svelte-archive/src/lib/components/filters/InitiativeDropdown.svelte
<script lang="ts">
	import Icon from '$lib/components/ui/Icon.svelte';
	import {
		initiatives,
		currentInitiativeId,
		currentInitiative,
		initiativeProgress,
		selectInitiative
	} from '$lib/stores/initiative';
	import { tasks as tasksStore } from '$lib/stores/tasks';
	import type { Initiative } from '$lib/types';

	// Special value for showing only unassigned tasks
	const UNASSIGNED_VALUE = '__unassigned__';

	// Dropdown open state
	let isOpen = $state(false);
	let dropdownRef = $state<HTMLDivElement | null>(null);

	// Get reactive values from stores
	let allInitiatives = $derived($initiatives);
	let selectedId = $derived($currentInitiativeId);
	let selectedInitiative = $derived($currentInitiative);
	let progress = $derived($initiativeProgress);
	let allTasks = $derived($tasksStore);

	// Sort initiatives: active first, then by title
	let sortedInitiatives = $derived(
		[...allInitiatives].sort((a, b) => {
			if (a.status === 'active' && b.status !== 'active') return -1;
			if (b.status === 'active' && a.status !== 'active') return 1;
			return a.title.localeCompare(b.title);
		})
	);

	// Count unassigned tasks (those with no initiative_id)
	let unassignedCount = $derived(
		allTasks.filter(t => !t.initiative_id).length
	);

	// Get task count for an initiative
	function getTaskCount(id: string): number {
		const p = progress.get(id);
		return p?.total ?? 0;
	}

	// Truncate long titles
	function truncateTitle(title: string, maxLength = 24): string {
		if (title.length <= maxLength) return title;
		return title.slice(0, maxLength - 1) + '…';
	}

	// Handle selection
	function handleSelect(id: string | null) {
		if (id === UNASSIGNED_VALUE) {
			// Special handling for unassigned - we'll use a sentinel value
			// The actual filtering happens in the parent component
			selectInitiative(UNASSIGNED_VALUE);
		} else {
			selectInitiative(id);
		}
		isOpen = false;
	}

	// Get display text for current selection
	let displayText = $derived.by(() => {
		if (selectedId === UNASSIGNED_VALUE) {
			return 'Unassigned';
		}
		if (selectedInitiative) {
			return truncateTitle(selectedInitiative.title);
		}
		return 'All initiatives';
	});

	// Is unassigned selected?
	let isUnassigned = $derived(selectedId === UNASSIGNED_VALUE);

	// Close dropdown when clicking outside
	function handleClickOutside(event: MouseEvent) {
		if (dropdownRef && !dropdownRef.contains(event.target as Node)) {
			isOpen = false;
		}
	}

	// Close dropdown on Escape
	function handleKeydown(event: KeyboardEvent) {
		if (event.key === 'Escape' && isOpen) {
			isOpen = false;
		}
	}

	$effect(() => {
		if (isOpen) {
			document.addEventListener('click', handleClickOutside);
			document.addEventListener('keydown', handleKeydown);
		}
		return () => {
			document.removeEventListener('click', handleClickOutside);
			document.removeEventListener('keydown', handleKeydown);
		};
	});
</script>

<div class="initiative-dropdown" bind:this={dropdownRef}>
	<button
		class="dropdown-trigger"
		class:active={selectedId !== null}
		onclick={() => (isOpen = !isOpen)}
		aria-haspopup="listbox"
		aria-expanded={isOpen}
	>
		<span class="trigger-text">{displayText}</span>
		<Icon name={isOpen ? 'chevron-up' : 'chevron-down'} size={14} />
	</button>

	{#if isOpen}
		<div class="dropdown-menu" role="listbox">
			<!-- All initiatives -->
			<button
				class="dropdown-item"
				class:selected={selectedId === null}
				onclick={() => handleSelect(null)}
				role="option"
				aria-selected={selectedId === null}
			>
				<span class="item-indicator">
					{#if selectedId === null}
						<span class="indicator-dot filled"></span>
					{:else}
						<span class="indicator-dot"></span>
					{/if}
				</span>
				<span class="item-label">All initiatives</span>
			</button>

			<!-- Unassigned tasks -->
			<button
				class="dropdown-item"
				class:selected={isUnassigned}
				onclick={() => handleSelect(UNASSIGNED_VALUE)}
				role="option"
				aria-selected={isUnassigned}
			>
				<span class="item-indicator">
					{#if isUnassigned}
						<span class="indicator-dot filled"></span>
					{:else}
						<span class="indicator-dot"></span>
					{/if}
				</span>
				<span class="item-label">Unassigned</span>
				<span class="item-count">{unassignedCount}</span>
			</button>

			{#if sortedInitiatives.length > 0}
				<div class="dropdown-divider"></div>

				<!-- Initiative list -->
				{#each sortedInitiatives as initiative (initiative.id)}
					{@const count = getTaskCount(initiative.id)}
					<button
						class="dropdown-item"
						class:selected={selectedId === initiative.id}
						onclick={() => handleSelect(initiative.id)}
						role="option"
						aria-selected={selectedId === initiative.id}
						title={initiative.title}
					>
						<span class="item-indicator">
							{#if selectedId === initiative.id}
								<span class="indicator-dot filled"></span>
							{:else}
								<span class="indicator-dot"></span>
							{/if}
						</span>
						<span class="item-label">{truncateTitle(initiative.title)}</span>
						<span class="item-count">{count}</span>
					</button>
				{/each}
			{/if}
		</div>
	{/if}
</div>

<style>
	.initiative-dropdown {
		position: relative;
	}

	.dropdown-trigger {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		padding: var(--space-2) var(--space-3);
		background: var(--bg-secondary);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-md);
		font-size: var(--text-sm);
		color: var(--text-primary);
		cursor: pointer;
		transition: all var(--duration-fast) var(--ease-out);
		min-width: 140px;
	}

	.dropdown-trigger:hover {
		border-color: var(--border-strong);
	}

	.dropdown-trigger:focus {
		outline: none;
		border-color: var(--accent-primary);
		box-shadow: 0 0 0 3px var(--accent-glow);
	}

	.dropdown-trigger.active {
		background: var(--accent-subtle);
		border-color: var(--accent-primary);
		color: var(--accent-primary);
	}

	.trigger-text {
		flex: 1;
		text-align: left;
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.dropdown-menu {
		position: absolute;
		top: calc(100% + var(--space-1));
		left: 0;
		min-width: 200px;
		max-height: 300px;
		overflow-y: auto;
		background: var(--bg-primary);
		border: 1px solid var(--border-default);
		border-radius: var(--radius-lg);
		box-shadow: var(--shadow-lg);
		z-index: var(--z-dropdown);
		padding: var(--space-1);
		animation: dropdown-enter var(--duration-fast) var(--ease-out);
	}

	@keyframes dropdown-enter {
		from {
			opacity: 0;
			transform: translateY(-4px);
		}
		to {
			opacity: 1;
			transform: translateY(0);
		}
	}

	.dropdown-item {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		width: 100%;
		padding: var(--space-2) var(--space-3);
		background: transparent;
		border: none;
		border-radius: var(--radius-md);
		font-size: var(--text-sm);
		color: var(--text-secondary);
		cursor: pointer;
		transition: all var(--duration-fast) var(--ease-out);
		text-align: left;
	}

	.dropdown-item:hover {
		background: var(--bg-tertiary);
		color: var(--text-primary);
	}

	.dropdown-item.selected {
		background: var(--accent-subtle);
		color: var(--accent-primary);
	}

	.item-indicator {
		display: flex;
		align-items: center;
		justify-content: center;
		width: 16px;
		height: 16px;
		flex-shrink: 0;
	}

	.indicator-dot {
		width: 8px;
		height: 8px;
		border-radius: 50%;
		border: 1.5px solid var(--text-muted);
		background: transparent;
		transition: all var(--duration-fast) var(--ease-out);
	}

	.indicator-dot.filled {
		background: var(--accent-primary);
		border-color: var(--accent-primary);
	}

	.dropdown-item:hover .indicator-dot {
		border-color: var(--text-secondary);
	}

	.dropdown-item.selected .indicator-dot {
		border-color: var(--accent-primary);
	}

	.item-label {
		flex: 1;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.item-count {
		font-size: var(--text-xs);
		font-family: var(--font-mono);
		color: var(--text-muted);
		padding: var(--space-0-5) var(--space-1-5);
		background: var(--bg-tertiary);
		border-radius: var(--radius-full);
		flex-shrink: 0;
	}

	.dropdown-item.selected .item-count {
		background: var(--accent-primary);
		color: var(--text-inverse);
	}

	.dropdown-divider {
		height: 1px;
		background: var(--border-subtle);
		margin: var(--space-1) var(--space-2);
	}
</style>

// web/src/components/board/InitiativeDropdown.tsx
/**
 * InitiativeDropdown component
 *
 * Dropdown to filter tasks by initiative.
 * Options: All initiatives, Unassigned, and each initiative with task count.
 */

import { useState, useCallback, useRef, useEffect, useMemo } from 'react';
import { Icon } from '@/components/ui/Icon';
import { useInitiatives, UNASSIGNED_INITIATIVE } from '@/stores';
import type { Task } from '@/lib/types';
import './InitiativeDropdown.css';

interface InitiativeDropdownProps {
	currentInitiativeId: string | null;
	onSelect: (id: string | null) => void;
	tasks: Task[];
}

export function InitiativeDropdown({
	currentInitiativeId,
	onSelect,
	tasks,
}: InitiativeDropdownProps) {
	const [isOpen, setIsOpen] = useState(false);
	const dropdownRef = useRef<HTMLDivElement>(null);
	const initiatives = useInitiatives();

	// Calculate task counts per initiative
	const taskCounts = useMemo(() => {
		const counts: Record<string, number> = { unassigned: 0 };
		for (const init of initiatives) {
			counts[init.id] = 0;
		}
		for (const task of tasks) {
			if (task.initiative_id && counts[task.initiative_id] !== undefined) {
				counts[task.initiative_id]++;
			} else {
				counts['unassigned']++;
			}
		}
		return counts;
	}, [tasks, initiatives]);

	// Sort initiatives: active first, then by title
	const sortedInitiatives = useMemo(() => {
		return [...initiatives].sort((a, b) => {
			// Active first
			if (a.status === 'active' && b.status !== 'active') return -1;
			if (b.status === 'active' && a.status !== 'active') return 1;
			// Then by title
			return a.title.localeCompare(b.title);
		});
	}, [initiatives]);

	// Get display label for current selection
	const displayLabel = useMemo(() => {
		if (!currentInitiativeId) return 'All initiatives';
		if (currentInitiativeId === UNASSIGNED_INITIATIVE) return 'Unassigned';
		const init = initiatives.find((i) => i.id === currentInitiativeId);
		return init ? truncateTitle(init.title, 24) : currentInitiativeId;
	}, [currentInitiativeId, initiatives]);

	const handleToggle = useCallback(() => {
		setIsOpen((prev) => !prev);
	}, []);

	const handleSelect = useCallback(
		(id: string | null) => {
			onSelect(id);
			setIsOpen(false);
		},
		[onSelect]
	);

	const handleKeydown = useCallback((e: React.KeyboardEvent) => {
		if (e.key === 'Escape') {
			setIsOpen(false);
		}
	}, []);

	// Close on click outside
	useEffect(() => {
		if (!isOpen) return;

		const handleClickOutside = (e: MouseEvent) => {
			if (dropdownRef.current && !dropdownRef.current.contains(e.target as Node)) {
				setIsOpen(false);
			}
		};

		document.addEventListener('mousedown', handleClickOutside);
		return () => document.removeEventListener('mousedown', handleClickOutside);
	}, [isOpen]);

	const isActive = currentInitiativeId !== null;

	return (
		<div className="initiative-dropdown" ref={dropdownRef} onKeyDown={handleKeydown}>
			<button
				type="button"
				className={`dropdown-trigger ${isActive ? 'active' : ''}`}
				onClick={handleToggle}
				aria-expanded={isOpen}
				aria-haspopup="listbox"
			>
				<Icon name="layers" size={16} />
				<span className="trigger-label">{displayLabel}</span>
				<Icon name="chevron-down" size={14} className={`chevron ${isOpen ? 'open' : ''}`} />
			</button>

			{isOpen && (
				<div className="dropdown-menu" role="listbox">
					{/* All initiatives */}
					<button
						type="button"
						className={`dropdown-option ${currentInitiativeId === null ? 'selected' : ''}`}
						onClick={() => handleSelect(null)}
						role="option"
						aria-selected={currentInitiativeId === null}
					>
						<span className="option-label">All initiatives</span>
					</button>

					{/* Unassigned */}
					<button
						type="button"
						className={`dropdown-option ${currentInitiativeId === UNASSIGNED_INITIATIVE ? 'selected' : ''}`}
						onClick={() => handleSelect(UNASSIGNED_INITIATIVE)}
						role="option"
						aria-selected={currentInitiativeId === UNASSIGNED_INITIATIVE}
					>
						<span className="option-label">Unassigned</span>
						<span className="option-count">{taskCounts['unassigned']}</span>
					</button>

					{sortedInitiatives.length > 0 && <div className="dropdown-divider" />}

					{/* Initiative list */}
					{sortedInitiatives.map((init) => (
						<button
							key={init.id}
							type="button"
							className={`dropdown-option ${currentInitiativeId === init.id ? 'selected' : ''}`}
							onClick={() => handleSelect(init.id)}
							role="option"
							aria-selected={currentInitiativeId === init.id}
							title={init.title}
						>
							<span className="option-label">{truncateTitle(init.title, 24)}</span>
							<span className="option-count">{taskCounts[init.id] || 0}</span>
						</button>
					))}
				</div>
			)}
		</div>
	);
}

function truncateTitle(title: string, maxLength: number): string {
	if (title.length <= maxLength) return title;
	return title.slice(0, maxLength - 1) + '\u2026';
}
