// web-react/src/pages/environment/Hooks.tsx
import { useState, useEffect, useCallback } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import {
	listHooks,
	getHookTypes,
	updateHook,
	deleteHook,
	type HooksMap,
	type HookEvent,
	type Hook,
	type HookEntry,
} from '@/lib/api';
import './Hooks.css';

type Scope = 'global' | 'project';

/**
 * Hooks page (/environment/hooks)
 *
 * Manages Claude Code hooks (settings.json format) at two levels:
 * - Global (~/.claude/settings.json)
 * - Project (.claude/settings.json)
 */
export function Hooks() {
	const [searchParams] = useSearchParams();
	const [hooks, setHooks] = useState<HooksMap>({});
	const [hookTypes, setHookTypes] = useState<HookEvent[]>([]);
	const [selectedEvent, setSelectedEvent] = useState<string | null>(null);
	const [loading, setLoading] = useState(true);
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const [success, setSuccess] = useState<string | null>(null);
	const [isEditing, setIsEditing] = useState(false);

	// Form state
	const [editingHooks, setEditingHooks] = useState<Hook[]>([]);

	const scope = searchParams.get('scope') as Scope | null;
	const isGlobal = scope === 'global';
	const scopeParam: 'global' | 'project' | undefined = isGlobal ? 'global' : 'project';

	const loadData = useCallback(async () => {
		setLoading(true);
		setError(null);

		try {
			const [hooksData, types] = await Promise.all([
				listHooks(scopeParam),
				getHookTypes(),
			]);
			setHooks(hooksData);
			setHookTypes(types);

			// Select first event with hooks if available
			const firstEvent = Object.keys(hooksData)[0] || types[0] || null;
			setSelectedEvent(firstEvent);
		} catch (e) {
			setError(e instanceof Error ? e.message : 'Failed to load hooks');
		} finally {
			setLoading(false);
		}
	}, [scopeParam]);

	useEffect(() => {
		loadData();
	}, [loadData]);

	const selectEvent = (event: string) => {
		setSelectedEvent(event);
		setIsEditing(false);
		setEditingHooks(hooks[event] || []);
	};

	const startEditing = () => {
		if (selectedEvent) {
			setEditingHooks(hooks[selectedEvent] || []);
			setIsEditing(true);
		}
	};

	const cancelEditing = () => {
		setIsEditing(false);
		if (selectedEvent) {
			setEditingHooks(hooks[selectedEvent] || []);
		}
	};

	const addHook = () => {
		setEditingHooks([
			...editingHooks,
			{
				matcher: '',
				hooks: [{ type: 'command', command: '' }],
			},
		]);
	};

	const removeHook = (index: number) => {
		setEditingHooks(editingHooks.filter((_, i) => i !== index));
	};

	const updateHookMatcher = (index: number, matcher: string) => {
		const updated = [...editingHooks];
		updated[index] = { ...updated[index], matcher };
		setEditingHooks(updated);
	};

	const addHookEntry = (hookIndex: number) => {
		const updated = [...editingHooks];
		updated[hookIndex] = {
			...updated[hookIndex],
			hooks: [...updated[hookIndex].hooks, { type: 'command', command: '' }],
		};
		setEditingHooks(updated);
	};

	const removeHookEntry = (hookIndex: number, entryIndex: number) => {
		const updated = [...editingHooks];
		updated[hookIndex] = {
			...updated[hookIndex],
			hooks: updated[hookIndex].hooks.filter((_, i) => i !== entryIndex),
		};
		setEditingHooks(updated);
	};

	const updateHookEntry = (
		hookIndex: number,
		entryIndex: number,
		entry: Partial<HookEntry>
	) => {
		const updated = [...editingHooks];
		updated[hookIndex] = {
			...updated[hookIndex],
			hooks: updated[hookIndex].hooks.map((h, i) =>
				i === entryIndex ? { ...h, ...entry } : h
			),
		};
		setEditingHooks(updated);
	};

	const handleSave = async () => {
		if (!selectedEvent) return;

		setSaving(true);
		setError(null);
		setSuccess(null);

		try {
			// Filter out empty hooks
			const validHooks = editingHooks.filter(
				(h) => h.hooks.length > 0 && h.hooks.some((e) => e.command.trim())
			);

			if (validHooks.length > 0) {
				await updateHook(selectedEvent, validHooks, scopeParam);
			} else {
				await deleteHook(selectedEvent, scopeParam);
			}

			await loadData();
			setIsEditing(false);
			setSuccess('Hooks saved successfully');
			setTimeout(() => setSuccess(null), 3000);
		} catch (e) {
			setError(e instanceof Error ? e.message : 'Failed to save hooks');
		} finally {
			setSaving(false);
		}
	};

	const getEventDescription = (event: string): string => {
		switch (event) {
			case 'PreToolUse':
				return 'Runs before Claude uses any tool';
			case 'PostToolUse':
				return 'Runs after Claude uses any tool';
			case 'PreCompact':
				return 'Runs before conversation is compacted';
			case 'PrePrompt':
				return 'Runs before the prompt is sent to Claude';
			case 'Stop':
				return 'Runs when Claude finishes';
			default:
				return '';
		}
	};

	return (
		<div className="hooks-page">
			<header className="hooks-header">
				<div className="header-content">
					<div>
						<h1>{isGlobal ? 'Global ' : ''}Claude Code Hooks</h1>
						<p className="subtitle">
							Configure hook commands that run at specific events
						</p>
					</div>
					<div className="header-actions">
						<div className="scope-toggle">
							<Link
								to="/environment/hooks"
								className={`scope-btn ${!isGlobal ? 'active' : ''}`}
							>
								Project
							</Link>
							<Link
								to="/environment/hooks?scope=global"
								className={`scope-btn ${isGlobal ? 'active' : ''}`}
							>
								Global
							</Link>
						</div>
					</div>
				</div>
			</header>

			{error && <div className="alert alert-error">{error}</div>}
			{success && <div className="alert alert-success">{success}</div>}

			{loading ? (
				<div className="loading-state">Loading hooks...</div>
			) : (
				<div className="hooks-layout">
					{/* Event List */}
					<aside className="event-list">
						<h2>Events</h2>
						<ul>
							{hookTypes.map((event) => (
								<li key={event}>
									<button
										className={`event-item ${selectedEvent === event ? 'selected' : ''}`}
										onClick={() => selectEvent(event)}
									>
										<span className="event-name">{event}</span>
										{hooks[event] && hooks[event].length > 0 && (
											<span className="hook-count">{hooks[event].length}</span>
										)}
									</button>
								</li>
							))}
						</ul>
					</aside>

					{/* Editor Panel */}
					<div className="editor-panel">
						{selectedEvent ? (
							<>
								<div className="editor-header">
									<div>
										<h2>{selectedEvent}</h2>
										<p className="event-desc">{getEventDescription(selectedEvent)}</p>
									</div>
									{!isEditing ? (
										<button className="btn btn-primary" onClick={startEditing}>
											Edit
										</button>
									) : (
										<div className="header-buttons">
											<button
												className="btn btn-secondary"
												onClick={cancelEditing}
												disabled={saving}
											>
												Cancel
											</button>
											<button
												className="btn btn-primary"
												onClick={handleSave}
												disabled={saving}
											>
												{saving ? 'Saving...' : 'Save'}
											</button>
										</div>
									)}
								</div>

								<div className="hooks-content">
									{isEditing ? (
										<div className="hooks-editor">
											{editingHooks.length === 0 ? (
												<div className="empty-editor">
													<p>No hooks configured for this event</p>
													<button className="btn btn-primary" onClick={addHook}>
														Add Hook
													</button>
												</div>
											) : (
												<>
													{editingHooks.map((hook, hookIndex) => (
														<div className="hook-card" key={hookIndex}>
															<div className="hook-card-header">
																<div className="form-group">
																	<label htmlFor={`matcher-${hookIndex}`}>
																		Matcher (glob pattern)
																	</label>
																	<input
																		id={`matcher-${hookIndex}`}
																		type="text"
																		value={hook.matcher}
																		onChange={(e) =>
																			updateHookMatcher(hookIndex, e.target.value)
																		}
																		placeholder="* (matches all tools)"
																	/>
																</div>
																<button
																	className="btn-icon btn-danger"
																	onClick={() => removeHook(hookIndex)}
																	title="Remove hook"
																>
																	&times;
																</button>
															</div>

															<div className="hook-entries">
																{hook.hooks.map((entry, entryIndex) => (
																	<div className="hook-entry" key={entryIndex}>
																		<select
																			value={entry.type}
																			onChange={(e) =>
																				updateHookEntry(hookIndex, entryIndex, {
																					type: e.target.value,
																				})
																			}
																		>
																			<option value="command">Command</option>
																			<option value="url">URL</option>
																		</select>
																		<input
																			type="text"
																			value={entry.command}
																			onChange={(e) =>
																				updateHookEntry(hookIndex, entryIndex, {
																					command: e.target.value,
																				})
																			}
																			placeholder={
																				entry.type === 'command'
																					? 'echo "Hook triggered"'
																					: 'https://example.com/webhook'
																			}
																		/>
																		<button
																			className="btn-icon"
																			onClick={() =>
																				removeHookEntry(hookIndex, entryIndex)
																			}
																			title="Remove entry"
																		>
																			&times;
																		</button>
																	</div>
																))}
																<button
																	className="btn-sm btn-secondary"
																	onClick={() => addHookEntry(hookIndex)}
																>
																	+ Add Command
																</button>
															</div>
														</div>
													))}
													<button className="btn btn-secondary" onClick={addHook}>
														+ Add Hook
													</button>
												</>
											)}
										</div>
									) : (
										<div className="hooks-view">
											{!hooks[selectedEvent] || hooks[selectedEvent].length === 0 ? (
												<div className="no-hooks">
													<p>No hooks configured for this event</p>
													<button className="btn btn-primary" onClick={startEditing}>
														Add Hook
													</button>
												</div>
											) : (
												<div className="hooks-list">
													{hooks[selectedEvent].map((hook, i) => (
														<div className="hook-view" key={i}>
															<div className="hook-matcher">
																<span className="label">Matcher:</span>
																<code>{hook.matcher || '*'}</code>
															</div>
															<div className="hook-commands">
																{hook.hooks.map((entry, j) => (
																	<div className="hook-command" key={j}>
																		<span className="entry-type">{entry.type}:</span>
																		<code>{entry.command}</code>
																	</div>
																))}
															</div>
														</div>
													))}
												</div>
											)}
										</div>
									)}
								</div>
							</>
						) : (
							<div className="no-selection">
								<p>Select an event type from the list</p>
							</div>
						)}
					</div>
				</div>
			)}
		</div>
	);
}

// web/src/routes/environment/claude/hooks/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import {
		listHooks,
		getHookTypes,
		createHook,
		deleteHook,
		type HooksMap,
		type HookEvent,
		type Hook,
		type HookEntry
	} from '$lib/api';

	let hooksMap = $state<HooksMap>({});
	let hookEvents = $state<HookEvent[]>([]);
	let selectedEvent = $state<HookEvent | null>(null);
	let selectedHookIndex = $state<number | null>(null);
	let isCreating = $state(false);
	let loading = $state(true);
	let saving = $state(false);
	let error = $state<string | null>(null);
	let success = $state<string | null>(null);

	// Form fields for a single hook
	let formMatcher = $state('');
	let formCommand = $state('');
	let formEvent = $state<HookEvent>('PreToolUse');

	// Get scope from URL params
	const scope = $derived($page.url.searchParams.get('scope') as 'global' | 'project' | null);
	const isGlobal = $derived(scope === 'global');
	const scopeParam = $derived(isGlobal ? 'global' : undefined);
	const settingsPath = $derived(isGlobal ? '~/.claude/settings.json' : '.claude/settings.json');

	onMount(async () => {
		try {
			// Read scope directly from URL on mount
			const urlScope = new URL(window.location.href).searchParams.get('scope');
			const initialScope = urlScope === 'global' ? 'global' : undefined;
			[hooksMap, hookEvents] = await Promise.all([listHooks(initialScope), getHookTypes()]);
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load hooks';
		} finally {
			loading = false;
		}
	});

	// Reload hooks when scope changes
	$effect(() => {
		if (!loading) {
			loadHooks();
		}
	});

	async function loadHooks() {
		try {
			hooksMap = await listHooks(scopeParam);
			selectedEvent = null;
			selectedHookIndex = null;
			isCreating = false;
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load hooks';
		}
	}

	function selectHook(event: HookEvent, index: number) {
		error = null;
		success = null;
		isCreating = false;
		selectedEvent = event;
		selectedHookIndex = index;

		const hook = hooksMap[event]?.[index];
		if (hook) {
			formMatcher = hook.matcher;
			formCommand = hook.hooks[0]?.command || '';
			formEvent = event;
		}
	}

	function startCreate() {
		error = null;
		success = null;
		selectedEvent = null;
		selectedHookIndex = null;
		isCreating = true;

		formMatcher = '';
		formCommand = '';
		formEvent = hookEvents[0] || 'PreToolUse';
	}

	async function handleSave() {
		if (!formMatcher.trim() || !formCommand.trim()) {
			error = 'Matcher and command are required';
			return;
		}

		saving = true;
		error = null;
		success = null;

		const hook: Hook = {
			matcher: formMatcher.trim(),
			hooks: [{ type: 'command', command: formCommand.trim() }]
		};

		try {
			await createHook(formEvent, hook, scopeParam);
			success = 'Hook saved successfully';
			hooksMap = await listHooks(scopeParam);

			if (isCreating) {
				isCreating = false;
				selectedEvent = formEvent;
				selectedHookIndex = (hooksMap[formEvent]?.length ?? 1) - 1;
			}
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to save hook';
		} finally {
			saving = false;
		}
	}

	async function handleDelete() {
		if (!selectedEvent) return;

		if (!confirm(`Delete hooks for "${selectedEvent}"?`)) return;

		saving = true;
		error = null;
		success = null;

		try {
			await deleteHook(selectedEvent, scopeParam);
			hooksMap = await listHooks(scopeParam);
			selectedEvent = null;
			selectedHookIndex = null;
			isCreating = false;
			success = 'Hook deleted successfully';
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to delete hook';
		} finally {
			saving = false;
		}
	}

	function getEventBadgeClass(event: string): string {
		if (event.startsWith('Pre')) return 'badge-pre';
		if (event.startsWith('Post')) return 'badge-post';
		return 'badge-other';
	}

	// Flatten hooks for display
	const flatHooks = $derived(Object.entries(hooksMap).flatMap(([event, hooks]) =>
		hooks.map((hook, index) => ({ event: event as HookEvent, hook, index }))
	));
</script>

<svelte:head>
	<title>{isGlobal ? 'Global ' : ''}Hooks - orc</title>
</svelte:head>

<div class="hooks-page">
	<header class="page-header">
		<div class="header-content">
			<div>
				<h1>{isGlobal ? 'Global ' : ''}Claude Code Hooks</h1>
				<p class="subtitle">Manage hooks in {settingsPath}</p>
			</div>
			<div class="header-actions">
				<div class="scope-toggle">
					<a href="/environment/claude/hooks" class="scope-btn" class:active={!isGlobal}>Project</a>
					<a href="/environment/claude/hooks?scope=global" class="scope-btn" class:active={isGlobal}>Global</a>
				</div>
				<button class="btn btn-primary" onclick={startCreate}>New Hook</button>
			</div>
		</div>
	</header>

	{#if error}
		<div class="alert alert-error">{error}</div>
	{/if}

	{#if success}
		<div class="alert alert-success">{success}</div>
	{/if}

	{#if loading}
		<div class="loading">Loading hooks...</div>
	{:else}
		<div class="hooks-layout">
			<!-- Hook List -->
			<aside class="hook-list">
				<h2>Hooks</h2>
				{#if flatHooks.length === 0}
					<p class="empty-message">No hooks configured</p>
				{:else}
					<ul>
						{#each flatHooks as { event, hook, index }}
							<li>
								<button
									class="hook-item"
									class:selected={selectedEvent === event && selectedHookIndex === index}
									onclick={() => selectHook(event, index)}
								>
									<span class="hook-name">{hook.matcher}</span>
									<span class="badge {getEventBadgeClass(event)}">{event}</span>
								</button>
							</li>
						{/each}
					</ul>
				{/if}
			</aside>

			<!-- Editor Panel -->
			<div class="editor-panel">
				{#if selectedEvent !== null || isCreating}
					<div class="editor-header">
						<h2>{isCreating ? 'New Hook' : formMatcher || 'Edit Hook'}</h2>
						{#if selectedEvent && !isCreating}
							<button class="btn btn-danger" onclick={handleDelete} disabled={saving}>
								Delete Event
							</button>
						{/if}
					</div>

					<form class="hook-form" onsubmit={(e) => { e.preventDefault(); handleSave(); }}>
						<div class="form-group">
							<label for="event">Event</label>
							<select id="event" bind:value={formEvent} disabled={!isCreating}>
								{#each hookEvents as event}
									<option value={event}>{event}</option>
								{/each}
							</select>
						</div>

						<div class="form-group">
							<label for="matcher">Matcher Pattern</label>
							<input
								id="matcher"
								type="text"
								bind:value={formMatcher}
								placeholder="Bash, Edit, *"
							/>
							<span class="help-text">Tool name pattern (use * for all tools)</span>
						</div>

						<div class="form-group">
							<label for="command">Command</label>
							<textarea
								id="command"
								bind:value={formCommand}
								placeholder="echo 'Hook executed'"
								rows="3"
							></textarea>
						</div>

						<div class="form-actions">
							<button type="submit" class="btn btn-primary" disabled={saving}>
								{saving ? 'Saving...' : isCreating ? 'Create' : 'Update'}
							</button>
						</div>
					</form>
				{:else}
					<div class="no-selection">
						<p>Select a hook from the list or create a new one.</p>
					</div>
				{/if}
			</div>
		</div>
	{/if}
</div>

<style>
	.hooks-page {
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	.page-header h1 {
		margin: 0;
		font-size: 1.5rem;
	}

	.header-content {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
	}

	.header-actions {
		display: flex;
		align-items: center;
		gap: 1rem;
	}

	.scope-toggle {
		display: flex;
		background: var(--bg-tertiary, rgba(0, 0, 0, 0.05));
		border-radius: 6px;
		padding: 2px;
	}

	.scope-btn {
		padding: 0.375rem 0.75rem;
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-secondary);
		text-decoration: none;
		border-radius: 4px;
		transition: all 0.15s ease;
	}

	.scope-btn:hover {
		color: var(--text-primary);
	}

	.scope-btn.active {
		background: var(--bg-primary);
		color: var(--text-primary);
		box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
	}

	.subtitle {
		margin: 0.5rem 0 0;
		color: var(--text-secondary);
		font-size: 0.875rem;
	}

	.alert {
		padding: 0.75rem 1rem;
		border-radius: 6px;
		font-size: 0.875rem;
	}

	.alert-error {
		background: var(--error-bg, #fee2e2);
		color: var(--error-text, #dc2626);
		border: 1px solid var(--error-border, #fecaca);
	}

	.alert-success {
		background: var(--success-bg, #dcfce7);
		color: var(--success-text, #16a34a);
		border: 1px solid var(--success-border, #bbf7d0);
	}

	.loading {
		text-align: center;
		padding: 3rem;
		color: var(--text-secondary);
	}

	.hooks-layout {
		display: grid;
		grid-template-columns: 250px 1fr;
		gap: 1.5rem;
		min-height: 500px;
	}

	/* Hook List */
	.hook-list {
		background: var(--bg-secondary);
		border-radius: 8px;
		padding: 1rem;
		border: 1px solid var(--border-color);
	}

	.hook-list h2 {
		font-size: 0.875rem;
		font-weight: 600;
		margin: 0 0 0.75rem;
		color: var(--text-secondary);
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.hook-list ul {
		list-style: none;
		padding: 0;
		margin: 0;
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.empty-message {
		color: var(--text-secondary);
		font-size: 0.875rem;
		font-style: italic;
	}

	.hook-item {
		display: flex;
		align-items: center;
		justify-content: space-between;
		width: 100%;
		padding: 0.5rem 0.75rem;
		background: transparent;
		border: none;
		border-radius: 6px;
		cursor: pointer;
		text-align: left;
		color: var(--text-primary);
		font-size: 0.875rem;
	}

	.hook-item:hover {
		background: var(--bg-tertiary, rgba(0, 0, 0, 0.05));
	}

	.hook-item.selected {
		background: var(--primary-bg, #dbeafe);
		color: var(--primary-text, #1d4ed8);
	}

	.hook-name {
		font-weight: 500;
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
	}

	.badge {
		font-size: 0.625rem;
		padding: 0.125rem 0.375rem;
		border-radius: 4px;
		text-transform: uppercase;
		font-weight: 600;
	}

	.badge-pre {
		background: var(--info-bg, #dbeafe);
		color: var(--info-text, #1d4ed8);
	}

	.badge-post {
		background: var(--success-bg, #dcfce7);
		color: var(--success-text, #16a34a);
	}

	.badge-other {
		background: var(--bg-tertiary, #e5e7eb);
		color: var(--text-secondary);
	}

	/* Editor Panel */
	.editor-panel {
		display: flex;
		flex-direction: column;
		background: var(--bg-secondary);
		border-radius: 8px;
		border: 1px solid var(--border-color);
		overflow: hidden;
	}

	.editor-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 1rem;
		border-bottom: 1px solid var(--border-color);
	}

	.editor-header h2 {
		margin: 0;
		font-size: 1rem;
	}

	.hook-form {
		padding: 1.5rem;
		display: flex;
		flex-direction: column;
		gap: 1rem;
	}

	.form-group {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.form-group label {
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-primary);
	}

	.form-group input,
	.form-group select,
	.form-group textarea {
		padding: 0.5rem 0.75rem;
		border: 1px solid var(--border-color);
		border-radius: 6px;
		font-size: 0.875rem;
		background: var(--bg-primary);
		color: var(--text-primary);
	}

	.form-group textarea {
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		resize: vertical;
	}

	.form-group input:focus,
	.form-group select:focus,
	.form-group textarea:focus {
		outline: none;
		border-color: var(--primary, #3b82f6);
	}

	.help-text {
		font-size: 0.75rem;
		color: var(--text-secondary);
	}

	.form-actions {
		padding-top: 0.5rem;
	}

	.btn {
		padding: 0.5rem 1rem;
		border-radius: 6px;
		font-size: 0.875rem;
		font-weight: 500;
		cursor: pointer;
		border: 1px solid transparent;
	}

	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn-primary {
		background: var(--primary, #3b82f6);
		color: white;
	}

	.btn-primary:hover:not(:disabled) {
		background: var(--primary-hover, #2563eb);
	}

	.btn-danger {
		background: var(--error-text, #dc2626);
		color: white;
	}

	.btn-danger:hover:not(:disabled) {
		background: #b91c1c;
	}

	.no-selection {
		display: flex;
		align-items: center;
		justify-content: center;
		height: 100%;
		padding: 3rem;
		text-align: center;
		color: var(--text-secondary);
	}

	@media (max-width: 768px) {
		.hooks-layout {
			grid-template-columns: 1fr;
		}

		.hook-list {
			max-height: 200px;
			overflow-y: auto;
		}
	}
</style>
