// web/src/pages/environment/Mcp.tsx
/**
 * MCP page (/environment/mcp)
 * Displays and edits MCP server configuration from .mcp.json
 */

import { useState, useEffect, useCallback } from 'react';
import { Button } from '@/components/ui/Button';
import { Input } from '@/components/ui/Input';
import { Icon } from '@/components/ui/Icon';
import { Modal } from '@/components/overlays/Modal';
import { toast } from '@/stores';
import {
	listMCPServers,
	getMCPServer,
	createMCPServer,
	updateMCPServer,
	deleteMCPServer,
	type MCPServerInfo,
	type MCPServerCreate,
} from '@/lib/api';
import './environment.css';

interface EnvVar {
	key: string;
	value: string;
}

export function Mcp() {
	const [servers, setServers] = useState<MCPServerInfo[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);

	// Editor modal state
	const [editingServer, setEditingServer] = useState<string | null>(null);
	const [isNewServer, setIsNewServer] = useState(false);
	const [formData, setFormData] = useState<MCPServerCreate>({
		name: '',
		type: 'stdio',
		command: '',
		args: [],
		env: {},
		disabled: false,
	});
	const [argsText, setArgsText] = useState('');
	const [envVars, setEnvVars] = useState<EnvVar[]>([]);
	const [saving, setSaving] = useState(false);
	const [editorLoading, setEditorLoading] = useState(false);

	const loadServers = useCallback(async () => {
		try {
			setLoading(true);
			setError(null);
			const data = await listMCPServers();
			setServers(data);
		} catch (err) {
			setError(err instanceof Error ? err.message : 'Failed to load MCP servers');
		} finally {
			setLoading(false);
		}
	}, []);

	useEffect(() => {
		loadServers();
	}, [loadServers]);

	const handleNew = () => {
		setFormData({
			name: '',
			type: 'stdio',
			command: '',
			args: [],
			env: {},
			disabled: false,
		});
		setArgsText('');
		setEnvVars([{ key: '', value: '' }]);
		setIsNewServer(true);
		setEditingServer('__new__');
	};

	const handleEdit = async (serverName: string) => {
		setEditorLoading(true);
		setEditingServer(serverName);
		setIsNewServer(false);
		try {
			const server = await getMCPServer(serverName);
			setFormData({
				name: server.name,
				type: server.type,
				command: server.command || '',
				args: server.args || [],
				env: server.env || {},
				url: server.url || '',
				disabled: server.disabled,
			});
			setArgsText((server.args || []).join('\n'));
			const envEntries = Object.entries(server.env || {}).map(([key, value]) => ({
				key,
				value,
			}));
			setEnvVars(envEntries.length > 0 ? envEntries : [{ key: '', value: '' }]);
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to load server');
			setEditingServer(null);
		} finally {
			setEditorLoading(false);
		}
	};

	const handleSave = async () => {
		if (!formData.name?.trim()) {
			toast.error('Server name is required');
			return;
		}

		// Build the request
		const args = argsText
			.split('\n')
			.map((a) => a.trim())
			.filter(Boolean);
		const env: Record<string, string> = {};
		envVars.forEach((v) => {
			if (v.key.trim()) {
				env[v.key.trim()] = v.value;
			}
		});

		const request: MCPServerCreate = {
			name: formData.name.trim(),
			type: formData.type,
			command: formData.type === 'stdio' ? formData.command : undefined,
			args: formData.type === 'stdio' && args.length > 0 ? args : undefined,
			env: Object.keys(env).length > 0 ? env : undefined,
			url: formData.type === 'sse' ? formData.url : undefined,
			disabled: formData.disabled,
		};

		try {
			setSaving(true);
			if (isNewServer) {
				await createMCPServer(request);
				toast.success('MCP server created');
			} else {
				await updateMCPServer(editingServer!, request);
				toast.success('MCP server updated');
			}
			setEditingServer(null);
			await loadServers();
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to save server');
		} finally {
			setSaving(false);
		}
	};

	const handleDelete = async (serverName: string) => {
		if (!confirm(`Delete MCP server "${serverName}"?`)) {
			return;
		}
		try {
			await deleteMCPServer(serverName);
			toast.success('MCP server deleted');
			await loadServers();
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to delete server');
		}
	};

	const handleToggle = async (server: MCPServerInfo) => {
		try {
			await updateMCPServer(server.name, { disabled: !server.disabled });
			toast.success(`${server.name} ${server.disabled ? 'enabled' : 'disabled'}`);
			await loadServers();
		} catch (err) {
			toast.error(err instanceof Error ? err.message : 'Failed to update server');
		}
	};

	const handleAddEnvVar = () => {
		setEnvVars([...envVars, { key: '', value: '' }]);
	};

	const handleRemoveEnvVar = (index: number) => {
		setEnvVars(envVars.filter((_, i) => i !== index));
	};

	const handleUpdateEnvVar = (index: number, field: 'key' | 'value', value: string) => {
		const updated = [...envVars];
		updated[index] = { ...updated[index], [field]: value };
		setEnvVars(updated);
	};

	if (loading) {
		return (
			<div className="page environment-mcp-page">
				<div className="env-loading">Loading MCP servers...</div>
			</div>
		);
	}

	if (error) {
		return (
			<div className="page environment-mcp-page">
				<div className="env-error">
					<p>{error}</p>
					<Button variant="secondary" onClick={loadServers}>
						Retry
					</Button>
				</div>
			</div>
		);
	}

	return (
		<div className="page environment-mcp-page">
			<div className="env-page-header">
				<div>
					<h3>MCP Servers</h3>
					<p className="env-page-description">
						Configure Model Context Protocol servers that extend Claude Code capabilities.
					</p>
				</div>
				<div className="env-page-header-actions">
					<Button variant="primary" onClick={handleNew}>
						<Icon name="plus" size={14} />
						Add Server
					</Button>
				</div>
			</div>

			{servers.length === 0 ? (
				<div className="env-empty">
					<Icon name="server" size={48} />
					<p>No MCP servers configured</p>
					<p className="env-empty-hint">
						Add servers to extend Claude Code with external tools and capabilities.
					</p>
				</div>
			) : (
				<div className="env-card-grid">
					{servers.map((server) => (
						<div
							key={server.name}
							className={`env-card mcp-card ${server.disabled ? 'disabled' : ''}`}
						>
							<div className="env-card-header">
								<h4 className="env-card-title">
									<Icon name={server.type === 'sse' ? 'globe' : 'terminal'} size={16} />
									{server.name}
								</h4>
								<div className="env-card-actions">
									<Button
										variant="ghost"
										size="sm"
										onClick={() => handleToggle(server)}
										aria-label={server.disabled ? 'Enable' : 'Disable'}
									>
										<Icon name={server.disabled ? 'eye' : 'eye-off'} size={14} />
									</Button>
									<Button
										variant="ghost"
										size="sm"
										onClick={() => handleEdit(server.name)}
									>
										<Icon name="edit" size={14} />
									</Button>
									<Button
										variant="ghost"
										size="sm"
										onClick={() => handleDelete(server.name)}
									>
										<Icon name="trash" size={14} />
									</Button>
								</div>
							</div>
							<div className="mcp-card-type">{server.type}</div>
							{server.type === 'stdio' && server.command && (
								<div className="mcp-card-command">{server.command}</div>
							)}
							{server.type === 'sse' && server.url && (
								<div className="mcp-card-url">{server.url}</div>
							)}
							<div className="mcp-card-meta">
								{server.args_count > 0 && (
									<span className="mcp-card-badge">
										{server.args_count} arg{server.args_count !== 1 ? 's' : ''}
									</span>
								)}
								{server.has_env && (
									<span className="mcp-card-badge">
										{server.env_count} env var{server.env_count !== 1 ? 's' : ''}
									</span>
								)}
								{server.disabled && (
									<span className="mcp-card-badge disabled">Disabled</span>
								)}
							</div>
						</div>
					))}
				</div>
			)}

			{/* Editor Modal */}
			<Modal
				open={editingServer !== null}
				onClose={() => setEditingServer(null)}
				title={isNewServer ? 'Add MCP Server' : `Edit ${editingServer}`}
				size="lg"
			>
				{editorLoading ? (
					<div className="env-loading">Loading server...</div>
				) : (
					<div className="mcp-editor">
						<div className="mcp-form-row">
							<div className="mcp-form-field">
								<label>Server Name</label>
								<Input
									value={formData.name || ''}
									onChange={(e) => setFormData({ ...formData, name: e.target.value })}
									placeholder="my-server"
									disabled={!isNewServer}
									size="sm"
								/>
							</div>
							<div className="mcp-form-field">
								<label>Type</label>
								<select
									value={formData.type || 'stdio'}
									onChange={(e) =>
										setFormData({ ...formData, type: e.target.value as 'stdio' | 'sse' })
									}
									className="input-field"
								>
									<option value="stdio">stdio (local process)</option>
									<option value="sse">sse (HTTP server)</option>
								</select>
							</div>
						</div>

						{formData.type === 'stdio' ? (
							<>
								<div className="mcp-form-field">
									<label>Command</label>
									<Input
										value={formData.command || ''}
										onChange={(e) =>
											setFormData({ ...formData, command: e.target.value })
										}
										placeholder="npx -y @anthropic/mcp-server"
										size="sm"
									/>
								</div>
								<div className="mcp-form-field">
									<label>Arguments (one per line)</label>
									<textarea
										value={argsText}
										onChange={(e) => setArgsText(e.target.value)}
										className="textarea-field mcp-args-textarea"
										placeholder="--flag&#10;value"
										rows={3}
									/>
								</div>
							</>
						) : (
							<div className="mcp-form-field">
								<label>Server URL</label>
								<Input
									value={formData.url || ''}
									onChange={(e) => setFormData({ ...formData, url: e.target.value })}
									placeholder="http://localhost:3000/sse"
									size="sm"
								/>
							</div>
						)}

						<div className="mcp-form-field">
							<div className="mcp-form-field-header">
								<label>Environment Variables</label>
								<Button variant="ghost" size="sm" onClick={handleAddEnvVar}>
									<Icon name="plus" size={14} />
									Add
								</Button>
							</div>
							<div className="mcp-env-vars">
								{envVars.map((v, i) => (
									<div key={i} className="mcp-env-row">
										<Input
											value={v.key}
											onChange={(e) => handleUpdateEnvVar(i, 'key', e.target.value)}
											placeholder="KEY"
											size="sm"
										/>
										<Input
											value={v.value}
											onChange={(e) => handleUpdateEnvVar(i, 'value', e.target.value)}
											placeholder="value"
											size="sm"
										/>
										<Button
											variant="ghost"
											size="sm"
											onClick={() => handleRemoveEnvVar(i)}
											aria-label="Remove"
										>
											<Icon name="x" size={14} />
										</Button>
									</div>
								))}
							</div>
						</div>

						<div className="mcp-form-field mcp-checkbox">
							<input
								type="checkbox"
								id="mcp-disabled"
								checked={formData.disabled || false}
								onChange={(e) => setFormData({ ...formData, disabled: e.target.checked })}
							/>
							<label htmlFor="mcp-disabled">Disabled</label>
						</div>

						<div className="mcp-editor-actions">
							<Button variant="secondary" onClick={() => setEditingServer(null)}>
								Cancel
							</Button>
							<Button variant="primary" onClick={handleSave} loading={saving}>
								{isNewServer ? 'Create Server' : 'Save Changes'}
							</Button>
						</div>
					</div>
				)}
			</Modal>
		</div>
	);
}

// web/src/routes/mcp/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import {
		listMCPServers,
		getMCPServer,
		createMCPServer,
		updateMCPServer,
		deleteMCPServer,
		type MCPServerInfo,
		type MCPServer
	} from '$lib/api';

	let servers: MCPServerInfo[] = [];
	let selectedServer: MCPServer | null = null;
	let isCreating = false;
	let loading = true;
	let saving = false;
	let error: string | null = null;
	let success: string | null = null;

	// Form fields
	let formName = '';
	let formType = 'stdio';
	let formCommand = '';
	let formArgs = '';
	let formUrl = '';
	let formHeaders = '';
	let formEnv: { key: string; value: string }[] = [];
	let formDisabled = false;

	onMount(async () => {
		try {
			servers = await listMCPServers();
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load MCP servers';
		} finally {
			loading = false;
		}
	});

	async function selectServerByName(name: string) {
		error = null;
		success = null;
		isCreating = false;

		try {
			selectedServer = await getMCPServer(name);
			formName = selectedServer.name;
			formType = selectedServer.type || 'stdio';
			formCommand = selectedServer.command || '';
			formArgs = selectedServer.args?.join('\n') || '';
			formUrl = selectedServer.url || '';
			formHeaders = selectedServer.headers?.join('\n') || '';
			formDisabled = selectedServer.disabled;

			// Convert env map to array
			if (selectedServer.env) {
				formEnv = Object.entries(selectedServer.env).map(([key, value]) => ({
					key,
					value
				}));
			} else {
				formEnv = [];
			}
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load server';
		}
	}

	function startCreate() {
		error = null;
		success = null;
		selectedServer = null;
		isCreating = true;

		formName = '';
		formType = 'stdio';
		formCommand = '';
		formArgs = '';
		formUrl = '';
		formHeaders = '';
		formEnv = [];
		formDisabled = false;
	}

	function addEnvVar() {
		formEnv = [...formEnv, { key: '', value: '' }];
	}

	function removeEnvVar(index: number) {
		formEnv = formEnv.filter((_, i) => i !== index);
	}

	async function handleSave() {
		if (!formName.trim()) {
			error = 'Server name is required';
			return;
		}

		if (formType === 'stdio' && !formCommand.trim()) {
			error = 'Command is required for stdio transport';
			return;
		}

		if ((formType === 'http' || formType === 'sse') && !formUrl.trim()) {
			error = 'URL is required for http/sse transport';
			return;
		}

		saving = true;
		error = null;
		success = null;

		// Parse args from newline-separated text
		const args = formArgs
			.split('\n')
			.map((a) => a.trim())
			.filter((a) => a);

		// Parse headers from newline-separated text
		const headers = formHeaders
			.split('\n')
			.map((h) => h.trim())
			.filter((h) => h);

		// Convert env array to map
		const env: Record<string, string> = {};
		for (const { key, value } of formEnv) {
			if (key.trim()) {
				env[key.trim()] = value;
			}
		}

		const serverData = {
			name: formName.trim(),
			type: formType,
			command: formType === 'stdio' ? formCommand.trim() : undefined,
			args: formType === 'stdio' && args.length > 0 ? args : undefined,
			url: formType !== 'stdio' ? formUrl.trim() : undefined,
			headers: formType !== 'stdio' && headers.length > 0 ? headers : undefined,
			env: Object.keys(env).length > 0 ? env : undefined,
			disabled: formDisabled
		};

		try {
			if (isCreating) {
				await createMCPServer(serverData);
				success = 'MCP server created successfully';
			} else if (selectedServer) {
				await updateMCPServer(selectedServer.name, serverData);
				success = 'MCP server updated successfully';
			}

			servers = await listMCPServers();
			isCreating = false;

			// Refresh selected server
			if (formName) {
				selectedServer = await getMCPServer(formName);
			}
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to save server';
		} finally {
			saving = false;
		}
	}

	async function handleDelete() {
		if (!selectedServer) return;

		if (!confirm(`Delete MCP server "${selectedServer.name}"?`)) return;

		saving = true;
		error = null;
		success = null;

		try {
			await deleteMCPServer(selectedServer.name);
			servers = await listMCPServers();
			selectedServer = null;
			isCreating = false;
			success = 'MCP server deleted successfully';
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to delete server';
		} finally {
			saving = false;
		}
	}

	function getTypeIcon(type: string): string {
		switch (type) {
			case 'stdio':
				return '>';
			case 'http':
				return 'H';
			case 'sse':
				return 'S';
			default:
				return '?';
		}
	}
</script>

<svelte:head>
	<title>MCP Servers - orc</title>
</svelte:head>

<div class="mcp-page">
	<header class="page-header">
		<div class="header-content">
			<div>
				<h1>MCP Servers</h1>
				<p class="subtitle">Configure Model Context Protocol servers for Claude Code</p>
			</div>
			<button class="btn btn-primary" on:click={startCreate}>New Server</button>
		</div>
	</header>

	{#if error}
		<div class="alert alert-error">{error}</div>
	{/if}

	{#if success}
		<div class="alert alert-success">{success}</div>
	{/if}

	{#if loading}
		<div class="loading">Loading MCP servers...</div>
	{:else}
		<div class="mcp-layout">
			<!-- Server List -->
			<aside class="server-list">
				<h2>Servers</h2>
				{#if servers.length === 0}
					<p class="empty-message">No MCP servers configured</p>
				{:else}
					<ul>
						{#each servers as server}
							<li>
								<button
									class="server-item"
									class:selected={selectedServer?.name === server.name}
									class:disabled={server.disabled}
									on:click={() => selectServerByName(server.name)}
								>
									<div class="server-header">
										<span class="type-badge" title={server.type}>
											{getTypeIcon(server.type)}
										</span>
										<span class="server-name">{server.name}</span>
									</div>
									<span class="server-detail">
										{#if server.type === 'stdio'}
											{server.command}
										{:else}
											{server.url}
										{/if}
									</span>
								</button>
							</li>
						{/each}
					</ul>
				{/if}
			</aside>

			<!-- Editor Panel -->
			<div class="editor-panel">
				{#if selectedServer || isCreating}
					<div class="editor-header">
						<h2>{isCreating ? 'New MCP Server' : selectedServer?.name}</h2>
						{#if selectedServer && !isCreating}
							<button class="btn btn-danger" on:click={handleDelete} disabled={saving}>
								Delete
							</button>
						{/if}
					</div>

					<form class="server-form" on:submit|preventDefault={handleSave}>
						<div class="form-row">
							<div class="form-group">
								<label for="name">Server Name</label>
								<input
									id="name"
									type="text"
									bind:value={formName}
									placeholder="my-mcp-server"
									disabled={!isCreating}
								/>
							</div>

							<div class="form-group">
								<label for="type">Transport Type</label>
								<select id="type" bind:value={formType}>
									<option value="stdio">stdio (local command)</option>
									<option value="http">http (REST endpoint)</option>
									<option value="sse">sse (Server-Sent Events)</option>
								</select>
							</div>
						</div>

						{#if formType === 'stdio'}
							<div class="form-group">
								<label for="command">Command</label>
								<input
									id="command"
									type="text"
									bind:value={formCommand}
									placeholder="npx"
								/>
								<span class="form-hint">Executable to run (e.g., npx, python, node)</span>
							</div>

							<div class="form-group">
								<label for="args">Arguments</label>
								<textarea
									id="args"
									bind:value={formArgs}
									placeholder="-y&#10;@modelcontextprotocol/server-github"
									rows="4"
								></textarea>
								<span class="form-hint">One argument per line</span>
							</div>
						{:else}
							<div class="form-group">
								<label for="url">URL</label>
								<input
									id="url"
									type="text"
									bind:value={formUrl}
									placeholder="https://example.com/mcp"
								/>
								<span class="form-hint">
									{formType === 'http' ? 'HTTP endpoint for MCP requests' : 'SSE endpoint URL'}
								</span>
							</div>

							<div class="form-group">
								<label for="headers">HTTP Headers</label>
								<textarea
									id="headers"
									bind:value={formHeaders}
									placeholder="Authorization: Bearer $&#123;TOKEN&#125;"
									rows="3"
								></textarea>
								<span class="form-hint">One header per line. Use $&#123;VAR&#125; for env vars</span>
							</div>
						{/if}

						<div class="form-group">
							<div class="env-header">
								<span class="form-label">Environment Variables</span>
								<button type="button" class="btn btn-sm" on:click={addEnvVar}>
									+ Add Variable
								</button>
							</div>
							{#if formEnv.length === 0}
								<p class="empty-env">No environment variables configured</p>
							{:else}
								<div class="env-list">
									{#each formEnv as envVar, i}
										<div class="env-row">
											<input
												type="text"
												bind:value={envVar.key}
												placeholder="KEY"
												class="env-key"
											/>
											<input
												type="text"
												bind:value={envVar.value}
												placeholder={'value or ${VAR}'}
												class="env-value"
											/>
											<button
												type="button"
												class="btn btn-icon"
												on:click={() => removeEnvVar(i)}
												title="Remove"
											>
												x
											</button>
										</div>
									{/each}
								</div>
							{/if}
							<span class="form-hint">
								Use $&#123;VAR&#125; or $&#123;VAR:-default&#125; to reference system env vars
							</span>
						</div>

						<div class="form-group">
							<label class="checkbox-label">
								<input type="checkbox" bind:checked={formDisabled} />
								<span>Disabled</span>
							</label>
							<span class="form-hint">
								Disabled servers are not loaded by Claude Code
							</span>
						</div>

						<div class="form-actions">
							<button type="submit" class="btn btn-primary" disabled={saving}>
								{saving ? 'Saving...' : isCreating ? 'Create' : 'Update'}
							</button>
						</div>
					</form>
				{:else}
					<div class="no-selection">
						<p>Select an MCP server from the list or create a new one.</p>
						<div class="hint">
							<p>MCP servers extend Claude Code with additional tools:</p>
							<ul>
								<li><strong>stdio</strong> - Local servers via command execution</li>
								<li><strong>http</strong> - Remote servers via HTTP requests</li>
								<li><strong>sse</strong> - Remote servers via Server-Sent Events</li>
							</ul>
						</div>
					</div>
				{/if}
			</div>
		</div>
	{/if}
</div>

<style>
	.mcp-page {
		display: flex;
		flex-direction: column;
		gap: 1.5rem;
	}

	.page-header h1 {
		margin: 0;
		font-size: 1.5rem;
	}

	.header-content {
		display: flex;
		justify-content: space-between;
		align-items: flex-start;
	}

	.subtitle {
		margin: 0.5rem 0 0;
		color: var(--text-secondary);
		font-size: 0.875rem;
	}

	.alert {
		padding: 0.75rem 1rem;
		border-radius: 6px;
		font-size: 0.875rem;
	}

	.alert-error {
		background: var(--error-bg, #fee2e2);
		color: var(--error-text, #dc2626);
		border: 1px solid var(--error-border, #fecaca);
	}

	.alert-success {
		background: var(--success-bg, #dcfce7);
		color: var(--success-text, #16a34a);
		border: 1px solid var(--success-border, #bbf7d0);
	}

	.loading {
		text-align: center;
		padding: 3rem;
		color: var(--text-secondary);
	}

	.mcp-layout {
		display: grid;
		grid-template-columns: 280px 1fr;
		gap: 1.5rem;
		min-height: 600px;
	}

	/* Server List */
	.server-list {
		background: var(--bg-secondary);
		border-radius: 8px;
		padding: 1rem;
		border: 1px solid var(--border-color);
	}

	.server-list h2 {
		font-size: 0.875rem;
		font-weight: 600;
		margin: 0 0 0.75rem;
		color: var(--text-secondary);
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}

	.server-list ul {
		list-style: none;
		padding: 0;
		margin: 0;
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.empty-message {
		color: var(--text-secondary);
		font-size: 0.875rem;
		font-style: italic;
	}

	.server-item {
		display: flex;
		flex-direction: column;
		align-items: flex-start;
		width: 100%;
		padding: 0.5rem 0.75rem;
		background: transparent;
		border: none;
		border-radius: 6px;
		cursor: pointer;
		text-align: left;
		color: var(--text-primary);
		font-size: 0.875rem;
		gap: 0.25rem;
	}

	.server-item:hover {
		background: var(--bg-tertiary, rgba(0, 0, 0, 0.05));
	}

	.server-item.selected {
		background: var(--primary-bg, #dbeafe);
		color: var(--primary-text, #1d4ed8);
	}

	.server-item.disabled {
		opacity: 0.5;
	}

	.server-header {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.type-badge {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 20px;
		height: 20px;
		font-size: 0.75rem;
		font-weight: 600;
		background: var(--bg-tertiary, rgba(0, 0, 0, 0.1));
		border-radius: 4px;
		font-family: monospace;
	}

	.server-name {
		font-weight: 500;
	}

	.server-detail {
		font-size: 0.75rem;
		color: var(--text-secondary);
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		max-width: 100%;
	}

	.server-item.selected .server-detail {
		color: var(--primary-text, #1d4ed8);
		opacity: 0.7;
	}

	/* Editor Panel */
	.editor-panel {
		display: flex;
		flex-direction: column;
		background: var(--bg-secondary);
		border-radius: 8px;
		border: 1px solid var(--border-color);
		overflow: hidden;
	}

	.editor-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
		padding: 1rem;
		border-bottom: 1px solid var(--border-color);
	}

	.editor-header h2 {
		margin: 0;
		font-size: 1rem;
	}

	.server-form {
		padding: 1.5rem;
		display: flex;
		flex-direction: column;
		gap: 1rem;
		overflow-y: auto;
	}

	.form-row {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: 1rem;
	}

	.form-group {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.form-group label,
	.form-label {
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-primary);
	}

	.form-group input,
	.form-group select,
	.form-group textarea {
		padding: 0.5rem 0.75rem;
		border: 1px solid var(--border-color);
		border-radius: 6px;
		font-size: 0.875rem;
		background: var(--bg-primary);
		color: var(--text-primary);
	}

	.form-group textarea {
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
		resize: vertical;
	}

	.form-group input:focus,
	.form-group select:focus,
	.form-group textarea:focus {
		outline: none;
		border-color: var(--primary, #3b82f6);
	}

	.form-hint {
		font-size: 0.75rem;
		color: var(--text-secondary);
	}

	.env-header {
		display: flex;
		align-items: center;
		justify-content: space-between;
	}

	.env-list {
		display: flex;
		flex-direction: column;
		gap: 0.5rem;
	}

	.env-row {
		display: grid;
		grid-template-columns: 1fr 2fr auto;
		gap: 0.5rem;
		align-items: center;
	}

	.env-key,
	.env-value {
		padding: 0.5rem 0.75rem;
		border: 1px solid var(--border-color);
		border-radius: 6px;
		font-size: 0.875rem;
		background: var(--bg-primary);
		color: var(--text-primary);
		font-family: 'JetBrains Mono', 'Fira Code', monospace;
	}

	.empty-env {
		color: var(--text-secondary);
		font-size: 0.875rem;
		font-style: italic;
		margin: 0;
	}

	.checkbox-label {
		display: flex;
		align-items: center;
		gap: 0.5rem;
		cursor: pointer;
	}

	.checkbox-label input {
		width: 16px;
		height: 16px;
	}

	.form-actions {
		padding-top: 0.5rem;
	}

	.btn {
		padding: 0.5rem 1rem;
		border-radius: 6px;
		font-size: 0.875rem;
		font-weight: 500;
		cursor: pointer;
		border: 1px solid transparent;
	}

	.btn-sm {
		padding: 0.375rem 0.75rem;
		font-size: 0.75rem;
	}

	.btn-icon {
		padding: 0.375rem 0.5rem;
		background: transparent;
		border: 1px solid var(--border-color);
		color: var(--text-secondary);
	}

	.btn-icon:hover {
		background: var(--error-bg, #fee2e2);
		color: var(--error-text, #dc2626);
	}

	.btn:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.btn-primary {
		background: var(--primary, #3b82f6);
		color: white;
	}

	.btn-primary:hover:not(:disabled) {
		background: var(--primary-hover, #2563eb);
	}

	.btn-danger {
		background: var(--error-text, #dc2626);
		color: white;
	}

	.btn-danger:hover:not(:disabled) {
		background: #b91c1c;
	}

	.no-selection {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		height: 100%;
		padding: 3rem;
		text-align: center;
		color: var(--text-secondary);
		gap: 1.5rem;
	}

	.no-selection .hint {
		font-size: 0.875rem;
		text-align: left;
	}

	.no-selection .hint ul {
		margin: 0.5rem 0 0;
		padding-left: 1.25rem;
	}

	.no-selection .hint li {
		margin: 0.25rem 0;
	}

	@media (max-width: 768px) {
		.mcp-layout {
			grid-template-columns: 1fr;
		}

		.server-list {
			max-height: 200px;
			overflow-y: auto;
		}

		.form-row {
			grid-template-columns: 1fr;
		}

		.env-row {
			grid-template-columns: 1fr 1fr auto;
		}
	}
</style>
