// web/src/routes/config/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { getConfig, updateConfig, type Config, type ConfigUpdateRequest } from '$lib/api';

	let config = $state<Config | null>(null);
	let loading = $state(true);
	let saving = $state(false);
	let error = $state<string | null>(null);
	let success = $state<string | null>(null);
	let editing = $state(false);

	// Edit form state
	let editProfile = $state('');
	let editGatesDefault = $state('');
	let editRetryEnabled = $state(false);
	let editRetryMax = $state(3);
	let editModel = $state('');
	let editMaxIterations = $state(10);
	let editTimeout = $state('');
	let editBranchPrefix = $state('');
	let editCommitPrefix = $state('');

	const profiles = ['auto', 'fast', 'safe', 'strict'];
	const gateTypes = ['auto', 'human', 'ai'];

	onMount(async () => {
		await loadConfig();
	});

	async function loadConfig() {
		loading = true;
		error = null;
		try {
			config = await getConfig();
			resetEditForm();
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load config';
		} finally {
			loading = false;
		}
	}

	function resetEditForm() {
		if (!config) return;
		editProfile = config.profile;
		editGatesDefault = config.automation.gates_default;
		editRetryEnabled = config.automation.retry_enabled;
		editRetryMax = config.automation.retry_max;
		editModel = config.execution.model;
		editMaxIterations = config.execution.max_iterations;
		editTimeout = config.execution.timeout;
		editBranchPrefix = config.git.branch_prefix;
		editCommitPrefix = config.git.commit_prefix;
	}

	function startEdit() {
		resetEditForm();
		editing = true;
		success = null;
	}

	function cancelEdit() {
		editing = false;
		resetEditForm();
	}

	async function saveConfig() {
		saving = true;
		error = null;
		success = null;

		try {
			const req: ConfigUpdateRequest = {
				profile: editProfile,
				automation: {
					gates_default: editGatesDefault,
					retry_enabled: editRetryEnabled,
					retry_max: editRetryMax
				},
				execution: {
					model: editModel,
					max_iterations: editMaxIterations,
					timeout: editTimeout
				},
				git: {
					branch_prefix: editBranchPrefix,
					commit_prefix: editCommitPrefix
				}
			};

			config = await updateConfig(req);
			editing = false;
			success = 'Configuration saved successfully';
			setTimeout(() => success = null, 3000);
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to save config';
		} finally {
			saving = false;
		}
	}
</script>

<svelte:head>
	<title>Config - orc</title>
</svelte:head>

<div class="page">
	<header class="page-header">
		<h1>Configuration</h1>
		{#if !editing && config}
			<button class="primary" onclick={startEdit}>Edit</button>
		{/if}
	</header>

	{#if success}
		<div class="success-banner">{success}</div>
	{/if}

	{#if error}
		<div class="error-banner">
			{error}
			<button onclick={() => error = null}>Dismiss</button>
		</div>
	{/if}

	{#if loading}
		<div class="loading">Loading configuration...</div>
	{:else if config}
		{#if editing}
			<!-- Edit Mode -->
			<form class="config-form" onsubmit={(e) => { e.preventDefault(); saveConfig(); }}>
				<section class="config-section">
					<h2>Automation</h2>
					<div class="form-group">
						<label for="profile">Profile</label>
						<select id="profile" bind:value={editProfile}>
							{#each profiles as p}
								<option value={p}>{p}</option>
							{/each}
						</select>
						<span class="hint">Controls overall automation level</span>
					</div>
					<div class="form-group">
						<label for="gates_default">Default Gate</label>
						<select id="gates_default" bind:value={editGatesDefault}>
							{#each gateTypes as g}
								<option value={g}>{g}</option>
							{/each}
						</select>
						<span class="hint">Gate type for phase transitions</span>
					</div>
					<div class="form-group checkbox">
						<input type="checkbox" id="retry_enabled" bind:checked={editRetryEnabled} />
						<label for="retry_enabled">Enable Retry</label>
						<span class="hint">Automatically retry failed phases</span>
					</div>
					<div class="form-group">
						<label for="retry_max">Max Retries</label>
						<input type="number" id="retry_max" bind:value={editRetryMax} min="0" max="10" />
						<span class="hint">Maximum retry attempts (0-10)</span>
					</div>
				</section>

				<section class="config-section">
					<h2>Execution</h2>
					<div class="form-group">
						<label for="model">Model</label>
						<input type="text" id="model" bind:value={editModel} placeholder="claude-sonnet-4-20250514" />
						<span class="hint">Claude model for execution</span>
					</div>
					<div class="form-group">
						<label for="max_iterations">Max Iterations</label>
						<input type="number" id="max_iterations" bind:value={editMaxIterations} min="1" max="100" />
						<span class="hint">Max iterations per phase (1-100)</span>
					</div>
					<div class="form-group">
						<label for="timeout">Timeout</label>
						<input type="text" id="timeout" bind:value={editTimeout} placeholder="30m" />
						<span class="hint">Task timeout (e.g., 30m, 1h)</span>
					</div>
				</section>

				<section class="config-section">
					<h2>Git</h2>
					<div class="form-group">
						<label for="branch_prefix">Branch Prefix</label>
						<input type="text" id="branch_prefix" bind:value={editBranchPrefix} placeholder="orc/" />
						<span class="hint">Prefix for task branches</span>
					</div>
					<div class="form-group">
						<label for="commit_prefix">Commit Prefix</label>
						<input type="text" id="commit_prefix" bind:value={editCommitPrefix} placeholder="[orc]" />
						<span class="hint">Prefix for commit messages</span>
					</div>
				</section>

				<div class="form-actions">
					<button type="button" onclick={cancelEdit} disabled={saving}>Cancel</button>
					<button type="submit" class="primary" disabled={saving}>
						{saving ? 'Saving...' : 'Save Changes'}
					</button>
				</div>
			</form>
		{:else}
			<!-- View Mode -->
			<div class="config-sections">
				<section class="config-section">
					<h2>Automation</h2>
					<table class="config-table">
						<tbody>
							<tr>
								<td class="label">Profile</td>
								<td class="value">{config.automation.profile}</td>
							</tr>
							<tr>
								<td class="label">Default Gate</td>
								<td class="value">{config.automation.gates_default}</td>
							</tr>
							<tr>
								<td class="label">Retry Enabled</td>
								<td class="value">{config.automation.retry_enabled ? 'Yes' : 'No'}</td>
							</tr>
							<tr>
								<td class="label">Max Retries</td>
								<td class="value">{config.automation.retry_max}</td>
							</tr>
						</tbody>
					</table>
				</section>

				<section class="config-section">
					<h2>Execution</h2>
					<table class="config-table">
						<tbody>
							<tr>
								<td class="label">Model</td>
								<td class="value mono">{config.execution.model}</td>
							</tr>
							<tr>
								<td class="label">Max Iterations</td>
								<td class="value">{config.execution.max_iterations}</td>
							</tr>
							<tr>
								<td class="label">Timeout</td>
								<td class="value">{config.execution.timeout}</td>
							</tr>
						</tbody>
					</table>
				</section>

				<section class="config-section">
					<h2>Git</h2>
					<table class="config-table">
						<tbody>
							<tr>
								<td class="label">Branch Prefix</td>
								<td class="value mono">{config.git.branch_prefix}</td>
							</tr>
							<tr>
								<td class="label">Commit Prefix</td>
								<td class="value mono">{config.git.commit_prefix}</td>
							</tr>
						</tbody>
					</table>
				</section>

				<section class="config-section">
					<h2>Version</h2>
					<p class="version">{config.version}</p>
				</section>
			</div>
		{/if}
	{/if}
</div>

<style>
	.page {
		max-width: 700px;
	}

	.page-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
		margin-bottom: 2rem;
	}

	h1 {
		font-size: 1.5rem;
		font-weight: 600;
	}

	.config-sections, .config-form {
		display: flex;
		flex-direction: column;
		gap: 2rem;
	}

	.config-section {
		background: var(--bg-secondary);
		border: 1px solid var(--border-color);
		border-radius: 8px;
		padding: 1.25rem;
	}

	.config-section h2 {
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-secondary);
		text-transform: uppercase;
		letter-spacing: 0.05em;
		margin-bottom: 1rem;
	}

	.config-table {
		width: 100%;
		border-collapse: collapse;
	}

	.config-table tr {
		border-bottom: 1px solid var(--border-color);
	}

	.config-table tr:last-child {
		border-bottom: none;
	}

	.config-table td {
		padding: 0.75rem 0;
	}

	.config-table .label {
		color: var(--text-secondary);
		font-size: 0.875rem;
		width: 40%;
	}

	.config-table .value {
		color: var(--text-primary);
		font-weight: 500;
	}

	.config-table .value.mono {
		font-family: var(--font-mono);
		font-size: 0.875rem;
	}

	.version {
		font-family: var(--font-mono);
		font-size: 0.875rem;
		color: var(--text-secondary);
	}

	/* Form styles */
	.form-group {
		margin-bottom: 1rem;
	}

	.form-group:last-child {
		margin-bottom: 0;
	}

	.form-group label {
		display: block;
		font-size: 0.875rem;
		font-weight: 500;
		color: var(--text-primary);
		margin-bottom: 0.375rem;
	}

	.form-group.checkbox {
		display: flex;
		align-items: center;
		gap: 0.5rem;
	}

	.form-group.checkbox label {
		display: inline;
		margin-bottom: 0;
	}

	.form-group.checkbox .hint {
		flex: 1;
	}

	.form-group input[type="text"],
	.form-group input[type="number"],
	.form-group select {
		width: 100%;
		padding: 0.625rem 0.75rem;
		background: var(--bg-tertiary);
		border: 1px solid var(--border-color);
		border-radius: 6px;
		color: var(--text-primary);
		font-size: 0.875rem;
	}

	.form-group input:focus,
	.form-group select:focus {
		outline: none;
		border-color: var(--accent-primary);
	}

	.form-group input[type="checkbox"] {
		width: 1rem;
		height: 1rem;
		accent-color: var(--accent-primary);
	}

	.form-group .hint {
		display: block;
		font-size: 0.75rem;
		color: var(--text-muted);
		margin-top: 0.25rem;
	}

	.form-actions {
		display: flex;
		justify-content: flex-end;
		gap: 0.75rem;
	}

	.success-banner {
		background: rgba(63, 185, 80, 0.1);
		border: 1px solid var(--accent-success);
		border-radius: 6px;
		padding: 0.75rem 1rem;
		margin-bottom: 1rem;
		color: var(--accent-success);
	}

	.error-banner {
		background: rgba(248, 81, 73, 0.1);
		border: 1px solid var(--accent-danger);
		border-radius: 6px;
		padding: 0.75rem 1rem;
		margin-bottom: 1rem;
		display: flex;
		justify-content: space-between;
		align-items: center;
		color: var(--accent-danger);
	}

	.error-banner button {
		background: transparent;
		border: none;
		color: var(--accent-danger);
		padding: 0.25rem 0.5rem;
	}

	.loading {
		text-align: center;
		padding: 3rem;
		color: var(--text-secondary);
	}
</style>

// web-react/src/pages/environment/Config.tsx
import { useState, useEffect, useCallback } from 'react';
import {
	getConfig,
	updateConfig,
	type Config as ConfigType,
	type ConfigUpdateRequest,
} from '@/lib/api';
import './Config.css';

/**
 * Config page (/environment/config)
 *
 * Manages orc configuration (.orc/config.yaml)
 * - Automation profiles
 * - Timeouts
 * - Git settings
 * - Worktree settings
 * - Completion settings
 */
export function Config() {
	const [config, setConfig] = useState<ConfigType | null>(null);
	const [loading, setLoading] = useState(true);
	const [saving, setSaving] = useState(false);
	const [error, setError] = useState<string | null>(null);
	const [success, setSuccess] = useState<string | null>(null);

	// Form state
	const [profile, setProfile] = useState('auto');
	const [gatesDefault, setGatesDefault] = useState('default');
	const [retryEnabled, setRetryEnabled] = useState(true);
	const [retryMax, setRetryMax] = useState(3);
	const [model, setModel] = useState('');
	const [maxIterations, setMaxIterations] = useState(10);
	const [timeout, setTimeout] = useState('');
	const [branchPrefix, setBranchPrefix] = useState('orc/');
	const [commitPrefix, setCommitPrefix] = useState('[orc]');
	const [worktreeEnabled, setWorktreeEnabled] = useState(true);
	const [worktreeDir, setWorktreeDir] = useState('.orc/worktrees');
	const [cleanupOnComplete, setCleanupOnComplete] = useState(true);
	const [cleanupOnFail, setCleanupOnFail] = useState(false);
	const [completionAction, setCompletionAction] = useState('pr');
	const [targetBranch, setTargetBranch] = useState('main');
	const [deleteBranch, setDeleteBranch] = useState(true);
	const [phaseMax, setPhaseMax] = useState('');
	const [turnMax, setTurnMax] = useState('');
	const [idleWarning, setIdleWarning] = useState('');
	const [heartbeatInterval, setHeartbeatInterval] = useState('');
	const [idleTimeout, setIdleTimeout] = useState('');

	const loadConfig = useCallback(async () => {
		setLoading(true);
		setError(null);

		try {
			const configData = await getConfig();
			setConfig(configData);

			// Populate form
			setProfile(configData.profile || 'auto');
			setGatesDefault(configData.automation?.gates_default || 'default');
			setRetryEnabled(configData.automation?.retry_enabled ?? true);
			setRetryMax(configData.automation?.retry_max ?? 3);
			setModel(configData.execution?.model || '');
			setMaxIterations(configData.execution?.max_iterations ?? 10);
			setTimeout(configData.execution?.timeout || '');
			setBranchPrefix(configData.git?.branch_prefix || 'orc/');
			setCommitPrefix(configData.git?.commit_prefix || '[orc]');
			setWorktreeEnabled(configData.worktree?.enabled ?? true);
			setWorktreeDir(configData.worktree?.dir || '.orc/worktrees');
			setCleanupOnComplete(configData.worktree?.cleanup_on_complete ?? true);
			setCleanupOnFail(configData.worktree?.cleanup_on_fail ?? false);
			setCompletionAction(configData.completion?.action || 'pr');
			setTargetBranch(configData.completion?.target_branch || 'main');
			setDeleteBranch(configData.completion?.delete_branch ?? true);
			setPhaseMax(configData.timeouts?.phase_max || '');
			setTurnMax(configData.timeouts?.turn_max || '');
			setIdleWarning(configData.timeouts?.idle_warning || '');
			setHeartbeatInterval(configData.timeouts?.heartbeat_interval || '');
			setIdleTimeout(configData.timeouts?.idle_timeout || '');
		} catch (e) {
			setError(e instanceof Error ? e.message : 'Failed to load config');
		} finally {
			setLoading(false);
		}
	}, []);

	useEffect(() => {
		loadConfig();
	}, [loadConfig]);

	const handleSave = async () => {
		setSaving(true);
		setError(null);
		setSuccess(null);

		const update: ConfigUpdateRequest = {
			profile,
			automation: {
				gates_default: gatesDefault,
				retry_enabled: retryEnabled,
				retry_max: retryMax,
			},
			execution: {
				model: model || undefined,
				max_iterations: maxIterations,
				timeout: timeout || undefined,
			},
			git: {
				branch_prefix: branchPrefix,
				commit_prefix: commitPrefix,
			},
			worktree: {
				enabled: worktreeEnabled,
				dir: worktreeDir,
				cleanup_on_complete: cleanupOnComplete,
				cleanup_on_fail: cleanupOnFail,
			},
			completion: {
				action: completionAction,
				target_branch: targetBranch,
				delete_branch: deleteBranch,
			},
			timeouts: {
				phase_max: phaseMax || undefined,
				turn_max: turnMax || undefined,
				idle_warning: idleWarning || undefined,
				heartbeat_interval: heartbeatInterval || undefined,
				idle_timeout: idleTimeout || undefined,
			},
		};

		try {
			await updateConfig(update);
			await loadConfig();
			setSuccess('Configuration saved successfully');
			globalThis.setTimeout(() => setSuccess(null), 3000);
		} catch (e) {
			setError(e instanceof Error ? e.message : 'Failed to save config');
		} finally {
			setSaving(false);
		}
	};

	const profiles = [
		{ value: 'auto', label: 'Auto', desc: 'Fully automated' },
		{ value: 'fast', label: 'Fast', desc: 'Minimal gates, speed over safety' },
		{ value: 'safe', label: 'Safe', desc: 'AI reviews, human for merge' },
		{ value: 'strict', label: 'Strict', desc: 'Human gates on spec/review/merge' },
	];

	return (
		<div className="config-page">
			<header className="config-header">
				<div className="header-content">
					<div>
						<h1>Orc Configuration</h1>
						<p className="subtitle">
							Manage orchestrator settings in .orc/config.yaml
						</p>
					</div>
					<button className="btn btn-primary" onClick={handleSave} disabled={saving}>
						{saving ? 'Saving...' : 'Save'}
					</button>
				</div>
			</header>

			{error && <div className="alert alert-error">{error}</div>}
			{success && <div className="alert alert-success">{success}</div>}

			{loading ? (
				<div className="loading-state">Loading configuration...</div>
			) : (
				<div className="config-sections">
					{/* Automation Profile */}
					<section className="config-section">
						<h2>Automation Profile</h2>
						<div className="profile-grid">
							{profiles.map((p) => (
								<label
									key={p.value}
									className={`profile-card ${profile === p.value ? 'selected' : ''}`}
								>
									<input
										type="radio"
										name="profile"
										value={p.value}
										checked={profile === p.value}
										onChange={(e) => setProfile(e.target.value)}
									/>
									<div className="profile-info">
										<span className="profile-name">{p.label}</span>
										<span className="profile-desc">{p.desc}</span>
									</div>
								</label>
							))}
						</div>
					</section>

					{/* Gates & Retry */}
					<section className="config-section">
						<h2>Gates & Retry</h2>
						<div className="form-grid">
							<div className="form-group">
								<label htmlFor="gates-default">Default Gates</label>
								<select
									id="gates-default"
									value={gatesDefault}
									onChange={(e) => setGatesDefault(e.target.value)}
								>
									<option value="default">Default</option>
									<option value="none">None</option>
									<option value="spec">Spec only</option>
									<option value="review">Review only</option>
									<option value="all">All</option>
								</select>
							</div>

							<div className="form-group">
								<label htmlFor="retry-max">Max Retries</label>
								<input
									id="retry-max"
									type="number"
									min={0}
									max={10}
									value={retryMax}
									onChange={(e) => setRetryMax(parseInt(e.target.value) || 0)}
								/>
							</div>

							<div className="form-group form-group-checkbox">
								<label>
									<input
										type="checkbox"
										checked={retryEnabled}
										onChange={(e) => setRetryEnabled(e.target.checked)}
									/>
									Enable automatic retry on failure
								</label>
							</div>
						</div>
					</section>

					{/* Execution */}
					<section className="config-section">
						<h2>Execution</h2>
						<div className="form-grid">
							<div className="form-group">
								<label htmlFor="model">Model</label>
								<input
									id="model"
									type="text"
									value={model}
									onChange={(e) => setModel(e.target.value)}
									placeholder="claude-sonnet-4-20250514"
								/>
							</div>

							<div className="form-group">
								<label htmlFor="max-iterations">Max Iterations</label>
								<input
									id="max-iterations"
									type="number"
									min={1}
									max={100}
									value={maxIterations}
									onChange={(e) => setMaxIterations(parseInt(e.target.value) || 1)}
								/>
							</div>

							<div className="form-group">
								<label htmlFor="timeout">Timeout</label>
								<input
									id="timeout"
									type="text"
									value={timeout}
									onChange={(e) => setTimeout(e.target.value)}
									placeholder="30m"
								/>
								<span className="form-hint">Go duration format (e.g., 30m, 1h)</span>
							</div>
						</div>
					</section>

					{/* Git */}
					<section className="config-section">
						<h2>Git Settings</h2>
						<div className="form-grid">
							<div className="form-group">
								<label htmlFor="branch-prefix">Branch Prefix</label>
								<input
									id="branch-prefix"
									type="text"
									value={branchPrefix}
									onChange={(e) => setBranchPrefix(e.target.value)}
									placeholder="orc/"
								/>
							</div>

							<div className="form-group">
								<label htmlFor="commit-prefix">Commit Prefix</label>
								<input
									id="commit-prefix"
									type="text"
									value={commitPrefix}
									onChange={(e) => setCommitPrefix(e.target.value)}
									placeholder="[orc]"
								/>
							</div>
						</div>
					</section>

					{/* Worktree */}
					<section className="config-section">
						<h2>Worktree Settings</h2>
						<div className="form-grid">
							<div className="form-group form-group-checkbox">
								<label>
									<input
										type="checkbox"
										checked={worktreeEnabled}
										onChange={(e) => setWorktreeEnabled(e.target.checked)}
									/>
									Enable git worktrees for task isolation
								</label>
							</div>

							<div className="form-group">
								<label htmlFor="worktree-dir">Worktree Directory</label>
								<input
									id="worktree-dir"
									type="text"
									value={worktreeDir}
									onChange={(e) => setWorktreeDir(e.target.value)}
									disabled={!worktreeEnabled}
								/>
							</div>

							<div className="form-group form-group-checkbox">
								<label>
									<input
										type="checkbox"
										checked={cleanupOnComplete}
										onChange={(e) => setCleanupOnComplete(e.target.checked)}
										disabled={!worktreeEnabled}
									/>
									Cleanup worktree on completion
								</label>
							</div>

							<div className="form-group form-group-checkbox">
								<label>
									<input
										type="checkbox"
										checked={cleanupOnFail}
										onChange={(e) => setCleanupOnFail(e.target.checked)}
										disabled={!worktreeEnabled}
									/>
									Cleanup worktree on failure
								</label>
							</div>
						</div>
					</section>

					{/* Completion */}
					<section className="config-section">
						<h2>Completion Settings</h2>
						<div className="form-grid">
							<div className="form-group">
								<label htmlFor="completion-action">Completion Action</label>
								<select
									id="completion-action"
									value={completionAction}
									onChange={(e) => setCompletionAction(e.target.value)}
								>
									<option value="pr">Create PR</option>
									<option value="merge">Merge directly</option>
									<option value="none">None</option>
								</select>
							</div>

							<div className="form-group">
								<label htmlFor="target-branch">Target Branch</label>
								<input
									id="target-branch"
									type="text"
									value={targetBranch}
									onChange={(e) => setTargetBranch(e.target.value)}
									placeholder="main"
								/>
							</div>

							<div className="form-group form-group-checkbox">
								<label>
									<input
										type="checkbox"
										checked={deleteBranch}
										onChange={(e) => setDeleteBranch(e.target.checked)}
									/>
									Delete branch after merge
								</label>
							</div>
						</div>
					</section>

					{/* Timeouts */}
					<section className="config-section">
						<h2>Timeouts</h2>
						<div className="form-grid">
							<div className="form-group">
								<label htmlFor="phase-max">Phase Max</label>
								<input
									id="phase-max"
									type="text"
									value={phaseMax}
									onChange={(e) => setPhaseMax(e.target.value)}
									placeholder="30m"
								/>
							</div>

							<div className="form-group">
								<label htmlFor="turn-max">Turn Max</label>
								<input
									id="turn-max"
									type="text"
									value={turnMax}
									onChange={(e) => setTurnMax(e.target.value)}
									placeholder="5m"
								/>
							</div>

							<div className="form-group">
								<label htmlFor="idle-warning">Idle Warning</label>
								<input
									id="idle-warning"
									type="text"
									value={idleWarning}
									onChange={(e) => setIdleWarning(e.target.value)}
									placeholder="2m"
								/>
							</div>

							<div className="form-group">
								<label htmlFor="heartbeat-interval">Heartbeat Interval</label>
								<input
									id="heartbeat-interval"
									type="text"
									value={heartbeatInterval}
									onChange={(e) => setHeartbeatInterval(e.target.value)}
									placeholder="10s"
								/>
							</div>

							<div className="form-group">
								<label htmlFor="idle-timeout">Idle Timeout</label>
								<input
									id="idle-timeout"
									type="text"
									value={idleTimeout}
									onChange={(e) => setIdleTimeout(e.target.value)}
									placeholder="5m"
								/>
							</div>
						</div>
					</section>
				</div>
			)}
		</div>
	);
}
