// web/src/lib/components/Dashboard.svelte
<script lang="ts">
	import { onMount, onDestroy } from 'svelte';
	import { goto } from '$app/navigation';
	import { getDashboardStats, listInitiatives, type DashboardStats } from '$lib/api';
	import { getWebSocket, type ConnectionStatus } from '$lib/websocket';
	import { tasks as tasksStore, tasksLoading } from '$lib/stores/tasks';
	import type { Task, Initiative } from '$lib/types';
	import {
		DashboardStats as StatsSection,
		DashboardQuickActions,
		DashboardActiveTasks,
		DashboardRecentActivity,
		DashboardSummary,
		DashboardInitiatives
	} from './dashboard';

	let stats = $state<DashboardStats | null>(null);
	let initiatives = $state<Initiative[]>([]);
	let loading = $state(true);
	let error = $state<string | null>(null);
	let wsStatus = $state<ConnectionStatus>('disconnected');
	let wsStatusCleanup: (() => void) | null = null;
	let wsEventCleanup: (() => void) | null = null;

	// Derive active and recent tasks from global store
	let activeTasks = $derived(
		$tasksStore
			.filter((t) => ['running', 'blocked', 'paused'].includes(t.status))
			.slice(0, 5)
	);

	let recentTasks = $derived(
		$tasksStore
			.filter((t) => ['completed', 'failed'].includes(t.status))
			.sort((a, b) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime())
			.slice(0, 5)
	);

	// Combined loading state
	let isLoading = $derived(loading || $tasksLoading);

	onMount(() => {
		loadDashboardData();

		// Subscribe to WebSocket status (events handled by layout)
		const ws = getWebSocket();
		wsStatusCleanup = ws.onStatusChange((status) => {
			wsStatus = status;
			if (status === 'connected') {
				// Refresh data on reconnect
				loadDashboardData();
			}
		});

		// Subscribe to task events to refresh initiatives when task status changes
		// Use 'all' to catch all task events (task_updated, task_created, task_deleted)
		wsEventCleanup = ws.on('all', (event) => {
			if ('event' in event && ['task_updated', 'task_created', 'task_deleted'].includes(event.event)) {
				// Refresh initiatives to update progress counts
				loadInitiatives();
			}
		});
		// Task list is kept up-to-date via file watcher WebSocket events
	});

	onDestroy(() => {
		if (wsStatusCleanup) {
			wsStatusCleanup();
		}
		if (wsEventCleanup) {
			wsEventCleanup();
		}
	});

	async function loadDashboardData() {
		try {
			// Load stats and initiatives in parallel
			const [statsData, initiativesData] = await Promise.all([
				getDashboardStats(),
				listInitiatives({ status: 'active' })
			]);
			stats = statsData;
			initiatives = initiativesData;
			loading = false;
		} catch (e) {
			error = e instanceof Error ? e.message : 'Failed to load dashboard';
			loading = false;
		}
	}

	async function loadInitiatives() {
		try {
			initiatives = await listInitiatives({ status: 'active' });
		} catch {
			// Silently fail - not critical
		}
	}

	function navigateToFiltered(status: string) {
		goto(`/?status=${status}`);
	}

	function navigateToDependencyFiltered(status: string) {
		goto(`/?dependency_status=${status}`);
	}

	function handleNewTask() {
		window.dispatchEvent(new CustomEvent('orc:new-task'));
	}

	function handleViewTasks() {
		goto('/');
	}
</script>

<div class="dashboard">
	{#if isLoading && !stats}
		<div class="loading">
			<div class="spinner"></div>
			<span>Loading dashboard...</span>
		</div>
	{:else if error}
		<div class="error">
			<p>{error}</p>
			<button onclick={loadDashboardData}>Retry</button>
		</div>
	{:else if stats}
		<StatsSection {stats} {wsStatus} onFilterClick={navigateToFiltered} onDependencyFilterClick={navigateToDependencyFiltered} />
		<DashboardQuickActions onNewTask={handleNewTask} onViewTasks={handleViewTasks} />
		<DashboardInitiatives {initiatives} />
		<DashboardActiveTasks tasks={activeTasks} />
		<DashboardRecentActivity tasks={recentTasks} />
		<DashboardSummary {stats} />
	{/if}
</div>

<style>
	.dashboard {
		max-width: 900px;
		display: flex;
		flex-direction: column;
		gap: var(--space-6);
	}

	.loading,
	.error {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
		gap: var(--space-4);
		padding: var(--space-16);
		text-align: center;
	}

	.spinner {
		width: 32px;
		height: 32px;
		border: 3px solid var(--border-default);
		border-top-color: var(--accent-primary);
		border-radius: 50%;
		animation: spin 1s linear infinite;
	}

	@keyframes spin {
		to {
			transform: rotate(360deg);
		}
	}
</style>

// web-react/src/pages/Dashboard.tsx
/**
 * Dashboard page (/dashboard)
 *
 * Displays quick stats, active tasks, recent activity, and initiatives.
 * Stats update in real-time via WebSocket.
 *
 * URL params:
 * - project: Project filter
 */

import { useState, useEffect, useCallback } from 'react';
import { useNavigate } from 'react-router-dom';
import { useTaskStore, useWsStatus } from '@/stores';
import { useWebSocket } from '@/hooks/useWebSocket';
import { getDashboardStats, listInitiatives, type DashboardStats } from '@/lib/api';
import type { Initiative, Task } from '@/lib/types';
import {
	DashboardStats as StatsSection,
	DashboardQuickActions,
	DashboardActiveTasks,
	DashboardRecentActivity,
	DashboardSummary,
	DashboardInitiatives,
} from '@/components/dashboard';
import './Dashboard.css';

// Filter tasks by status
const ACTIVE_STATUSES = ['running', 'blocked', 'paused'];
const RECENT_STATUSES = ['completed', 'failed'];

export function Dashboard() {
	const navigate = useNavigate();
	const wsStatus = useWsStatus();
	const { on } = useWebSocket();
	const tasks = useTaskStore((state) => state.tasks);

	const [stats, setStats] = useState<DashboardStats | null>(null);
	const [initiatives, setInitiatives] = useState<Initiative[]>([]);
	const [loading, setLoading] = useState(true);
	const [error, setError] = useState<string | null>(null);

	// Derive active and recent tasks from store
	const activeTasks = tasks
		.filter((t: Task) => ACTIVE_STATUSES.includes(t.status))
		.slice(0, 5);

	const recentTasks = tasks
		.filter((t: Task) => RECENT_STATUSES.includes(t.status))
		.sort((a: Task, b: Task) => new Date(b.updated_at).getTime() - new Date(a.updated_at).getTime())
		.slice(0, 5);

	const loadDashboardData = useCallback(async () => {
		try {
			// Load stats and initiatives in parallel
			const [statsData, initiativesData] = await Promise.all([
				getDashboardStats(),
				listInitiatives({ status: 'active' }),
			]);
			setStats(statsData);
			setInitiatives(initiativesData);
			setLoading(false);
			setError(null);
		} catch (e) {
			setError(e instanceof Error ? e.message : 'Failed to load dashboard');
			setLoading(false);
		}
	}, []);

	const loadInitiatives = useCallback(async () => {
		try {
			const data = await listInitiatives({ status: 'active' });
			setInitiatives(data);
		} catch {
			// Silently fail - not critical
		}
	}, []);

	// Initial load
	useEffect(() => {
		loadDashboardData();
	}, [loadDashboardData]);

	// Refresh data on WebSocket reconnect
	useEffect(() => {
		if (wsStatus === 'connected') {
			loadDashboardData();
		}
	}, [wsStatus, loadDashboardData]);

	// Subscribe to task events to refresh initiatives when task status changes
	useEffect(() => {
		const unsubscribe = on('all', (event) => {
			if (
				'event' in event &&
				['task_updated', 'task_created', 'task_deleted'].includes(event.event)
			) {
				// Refresh initiatives to update progress counts
				loadInitiatives();
				// Also refresh stats
				getDashboardStats().then(setStats).catch(() => {});
			}
		});
		return unsubscribe;
	}, [on, loadInitiatives]);

	const navigateToFiltered = (status: string) => {
		navigate(`/?status=${status}`);
	};

	const navigateToDependencyFiltered = (status: string) => {
		navigate(`/?dependency_status=${status}`);
	};

	const handleNewTask = () => {
		window.dispatchEvent(new CustomEvent('orc:new-task'));
	};

	const handleViewTasks = () => {
		navigate('/');
	};

	// Loading state
	if (loading && !stats) {
		return (
			<div className="dashboard">
				<div className="loading">
					<div className="spinner" />
					<span>Loading dashboard...</span>
				</div>
			</div>
		);
	}

	// Error state
	if (error) {
		return (
			<div className="dashboard">
				<div className="error">
					<p>{error}</p>
					<button onClick={loadDashboardData}>Retry</button>
				</div>
			</div>
		);
	}

	// Main dashboard content
	if (!stats) {
		return null;
	}

	return (
		<div className="dashboard">
			<StatsSection
				stats={stats}
				wsStatus={wsStatus}
				onFilterClick={navigateToFiltered}
				onDependencyFilterClick={navigateToDependencyFiltered}
			/>
			<DashboardQuickActions onNewTask={handleNewTask} onViewTasks={handleViewTasks} />
			<DashboardInitiatives initiatives={initiatives} />
			<DashboardActiveTasks tasks={activeTasks} />
			<DashboardRecentActivity tasks={recentTasks} />
			<DashboardSummary stats={stats} />
		</div>
	);
}
